import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

const translations = {
  en: {
    appTitle: 'AMS - Audit Management System',
    dashboard: 'Dashboard',
    admin: 'Admin',
    templates: 'Templates',
    masters: 'Masters',
    rbac: 'RBAC',
    users: 'Users',
    planning: 'Planning',
    myAudits: 'My Audits',
    hiaReview: 'HIA Review',
    compliance: 'Compliance',
    closure: 'Closure',
    reports: 'Reports',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    employeeCode: 'Employee Code',
    password: 'Password',
    signIn: 'Sign In',
    unauthorized: 'Unauthorized',
    notAuthorized: 'You are not authorized to access this page.',
    backToDashboard: 'Back to Dashboard',
    welcome: 'Welcome',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    approve: 'Approve',
    reject: 'Reject',
    search: 'Search',
    reset: 'Reset',
    actions: 'Actions',
    status: 'Status',
    created: 'Created',
    updated: 'Updated',
    loading: 'Loading...',
    noData: 'No data',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    edit: 'Edit',
    delete: 'Delete',
    create: 'Create',
    view: 'View',
    clone: 'Clone',
    publish: 'Publish',
    unpublish: 'Unpublish',
    draft: 'Draft',
    published: 'Published',
    active: 'Active',
    inactive: 'Inactive',
    export: 'Export',
    import: 'Import',
    download: 'Download',
    upload: 'Upload',
    filter: 'Filter',
    clearFilter: 'Clear Filter',
    total: 'Total',
    branch: 'Branch',
    branches: 'Branches',
    pacs: 'PACS',
    financialYear: 'Financial Year',
    auditType: 'Audit Type',
    plan: 'Plan',
    audit: 'Audit',
    observation: 'Observation',
    observations: 'Observations',
    risk: 'Risk',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    critical: 'Critical',
    age: 'Age',
    ageing: 'Ageing',
    certificate: 'Certificate',
    signature: 'Signature',
    form: 'Form',
    response: 'Response',
    responses: 'Responses',
    attachment: 'Attachment',
    attachments: 'Attachments',
    section: 'Section',
    sections: 'Sections',
    field: 'Field',
    fields: 'Fields',
    option: 'Option',
    options: 'Options',
    valueStatement: 'Value Statement',
    riskConfig: 'Risk Configuration',
    notification: 'Notification',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    gujarati: 'Gujarati',
    confirmDelete: 'Are you sure you want to delete this item?',
    operationSuccess: 'Operation completed successfully',
    requiredField: 'This field is required',
    selectOption: 'Select an option',
    dateFormat: 'DD/MM/YYYY',
    noNotifications: 'No notifications',
  },
  gu: {
    appTitle: 'AMS - ઓડિટ મેનેજમેન્ટ સિસ્ટમ',
    dashboard: 'ડેશબોર્ડ',
    admin: 'એડમિન',
    templates: 'ટેમ્પલેટ્સ',
    masters: 'માસ્ટર્સ',
    rbac: 'RBAC',
    users: 'વપરાશકર્તાઓ',
    planning: 'આયોજન',
    myAudits: 'મારા ઓડિટ',
    hiaReview: 'HIA સમીક્ષા',
    compliance: 'અનુપાલન',
    closure: 'સમાપ્તિ',
    reports: 'અહેવાલો',
    profile: 'પ્રોફાઇલ',
    logout: 'લોગઆઉટ',
    login: 'લોગિન',
    employeeCode: 'કર્મચારી કોડ',
    password: 'પાસવર્ડ',
    signIn: 'સાઇન ઇન',
    unauthorized: 'અનધિકૃત',
    notAuthorized: 'તમને આ પૃષ્ઠ access કરવાની અધિકૃતતા નથી.',
    backToDashboard: 'ડેશબોર્ડ પર પાછા જાઓ',
    welcome: 'સ્વાગત',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    submit: 'સબમિટ કરો',
    approve: 'મંજૂર કરો',
    reject: 'નામંજૂર કરો',
    search: 'શોધો',
    reset: 'રીસેટ',
    actions: 'ક્રિયાઓ',
    status: 'સ્થિતિ',
    created: 'બનાવ્યું',
    updated: 'અપડેટ કર્યું',
    loading: 'લોડ થઈ રહ્યું છે...',
    noData: 'કોઈ ડેટા નથી',
    confirm: 'ખાતરી કરો',
    yes: 'હા',
    no: 'ના',
    back: 'પાછા',
    edit: 'સંપાદિત કરો',
    delete: 'કાઢી નાખો',
    create: 'બનાવો',
    view: 'જુઓ',
    clone: 'ક્લોન કરો',
    publish: 'પ્રકાશિત કરો',
    unpublish: 'અપ્રકાશિત કરો',
    draft: 'ડ્રાફ્ટ',
    published: 'પ્રકાશિત',
    active: 'સક્રિય',
    inactive: 'નિષ્ક્રિય',
    export: 'નિકાસ',
    import: 'આયાત',
    download: 'ડાઉનલોડ',
    upload: 'અપલોડ',
    filter: 'ફિલ્ટર',
    clearFilter: 'ફિલ્ટર સાફ કરો',
    total: 'કુલ',
    branch: 'શાખા',
    branches: 'શાખાઓ',
    pacs: 'PACS',
    financialYear: 'નાણાકીય વર્ષ',
    auditType: 'ઓડિટ પ્રકાર',
    plan: 'યોજના',
    audit: 'ઓડિટ',
    observation: 'નિરિક્ષણ',
    observations: 'નિરિક્ષણો',
    risk: 'જોખમ',
    high: 'ઉચ્ચ',
    medium: 'મધ્યમ',
    low: 'નીચું',
    critical: 'ગંભીર',
    age: 'જૂનું',
    ageing: 'જૂનાપણું',
    certificate: 'પ્રમાણપત્ર',
    signature: 'સહી',
    form: 'ફોર્મ',
    response: 'પ્રતિભાવ',
    responses: 'પ્રતિભાવો',
    attachment: 'જોડાણ',
    attachments: 'જોડાણો',
    section: 'વિભાગ',
    sections: 'વિભાગો',
    field: 'ફીલ્ડ',
    fields: 'ફીલ્ડ્સ',
    option: 'વિકલ્પ',
    options: 'વિકલ્પો',
    valueStatement: 'મૂલ્ય વિધાન',
    riskConfig: 'જોખમ રૂપરેખાંકન',
    notification: 'સૂચના',
    notifications: 'સૂચનાઓ',
    language: 'ભાષા',
    english: 'અંગ્રેજી',
    gujarati: 'ગુજરાતી',
    confirmDelete: 'શું તમે ખરેખર આ આઇટમ કાઢી નાખવા માંગો છો?',
    operationSuccess: 'કામગીરી સફળતાપૂર્વક પૂર્ણ થઈ',
    requiredField: 'આ ફીલ્ડ જરૂરી છે',
    selectOption: 'એક વિકલ્પ પસંદ કરો',
    dateFormat: 'DD/MM/YYYY',
    noNotifications: 'કોઈ સૂચનાઓ નથી',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('ams_language') || 'en';
  });

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => {
      const next = prev === 'en' ? 'gu' : 'en';
      localStorage.setItem('ams_language', next);
      return next;
    });
  }, []);

  const t = useCallback((key, fallback) => {
    return (translations[language] && translations[language][key]) || fallback || key;
  }, [language]);

  const value = {
    language,
    setLanguage,
    toggleLanguage,
    t,
    translations: translations[language] || translations.en,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export default LanguageContext;
