const Template = require('../models/Template');

module.exports = async function createInspectionMemoTemplate(auditType) {
  const template = await Template.create({
    auditType: auditType._id,
    version: 1,
    status: 'Published',
    publishedAt: new Date(),
    sections: [],
  });

  const sections = [
    {
      code: 'SEC_IM_HEADER',
      titleEn: 'Internal Inspection Memo Header',
      titleGu: 'આંતરિક ઇન્સ્પેક્શન મેમો હેડર',
      sequence: 1,
      fields: [
        { code: 'FLD_IM_BRANCH_NAME', labelEn: 'Branch Name', labelGu: 'શાખાનું નામ', fieldType: 'TEXT_SHORT', isMandatory: true, sequence: 1 },
        { code: 'FLD_IM_OFFICER_NAME', labelEn: 'Inspecting Officer Name', labelGu: 'ઇન્સ્પેક્શન કરનાર અધિકારીનું નામ', fieldType: 'TEXT_SHORT', isMandatory: true, sequence: 2 },
        { code: 'FLD_IM_INSPECTION_DATE', labelEn: 'Inspection Date', labelGu: 'ઇન્સ્પેક્શન તારીખ', fieldType: 'DATE', isMandatory: true, sequence: 3 },
        { code: 'FLD_IM_PERIOD_FROM', labelEn: 'Internal Inspection Period From', labelGu: 'આંતરિક ઇન્સ્પેક્શન પિરિયડ થી', fieldType: 'DATE', sequence: 4 },
        { code: 'FLD_IM_PERIOD_TO', labelEn: 'Internal Inspection Period To', labelGu: 'આંતરિક ઇન્સ્પેક્શન પિરિયડ સુધી', fieldType: 'DATE', sequence: 5 },
      ],
    },
    {
      code: 'SEC_IM_CASH_SILAK',
      titleEn: 'Account Dept - (1) Cash / Silak Verification',
      titleGu: 'એકાઉન્ટ વિભાગ - (૧) રોકડ સિલ્વિક તપાસણી',
      sequence: 2,
      fields: [
        { code: 'FLD_IM_SILAK_HAND', labelEn: 'Silak limit - cash on hand', labelGu: 'સિલ્વિક મર્યાદા હાથ પર રકમ છે', fieldType: 'CURRENCY', sequence: 1 },
        { code: 'FLD_IM_SILAK_BANK', labelEn: 'Silak limit - amount in banks', labelGu: 'સિલ્વિક મર્યાદા બેન્કોમાં રકમ છે', fieldType: 'CURRENCY', sequence: 2 },
        { code: 'FLD_IM_SILAK_KEPT', labelEn: 'Where is silak kept (safe)', labelGu: 'સિલ્વિક ક્યા રખાય છે - તિજોરી', fieldType: 'TEXT_SHORT', sequence: 3 },
        { code: 'FLD_IM_OPEN_CLOSE_SILAK', labelEn: 'Opening/closing silak on inspection date, amount, in-transit', labelGu: 'આંતરિક ઇન્સ્પેક્શનની તારીખની ખૂલતી/બંધ સિલ્વિક તારીખ, રકમ છે, વેહંટમાં આવેલ છે', fieldType: 'TEXT_LONG', sequence: 4 },
        { code: 'FLD_IM_CASH_REPORT_BGL', labelEn: 'Verify silak as per cash report B.G.L.', labelGu: 'કેશ રિપોર્ટ બી.જી.એલ. મુજબ સિલ્વિક તપાસવી', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_IM_SILAK_FIGURES', labelEn: 'In figures', labelGu: 'અંકે છે', fieldType: 'CURRENCY', sequence: 6 },
        {
          code: 'FLD_IM_DENOM_GRID', labelEn: 'Denomination Cash Summary', labelGu: 'ડીનોમીનેશન કેશ સમરી', fieldType: 'GRID', sequence: 7,
          gridColumns: [
            { code: 'COL_DENOM', labelEn: 'Denomination', labelGu: 'ડીનોમીનેશન', columnType: 'TEXT_SHORT', sequence: 1 },
            { code: 'COL_COUNT', labelEn: 'Count (X)', labelGu: 'સંખ્યા (X)', columnType: 'NUMBER', sequence: 2 },
            { code: 'COL_AMOUNT', labelEn: 'Amount (=)', labelGu: 'રકમ (=)', columnType: 'CURRENCY', sequence: 3 },
          ],
          seedRows: [
            { denom: '૫૦', count: '', amount: '' },
            { denom: '૨૦', count: '', amount: '' },
            { denom: '૧૦૦', count: '', amount: '' },
            { denom: '૫૦', count: '', amount: '' },
            { denom: '૨૦', count: '', amount: '' },
            { denom: '૧૦', count: '', amount: '' },
            { denom: '૫', count: '', amount: '' },
            { denom: 'પરચૂરાણુ', count: '', amount: '' },
            { denom: 'કુલ', count: '', amount: '' },
          ],
        },
        { code: 'FLD_IM_CASH_SUMMARY_PAGE', labelEn: 'Cash summary page no.', labelGu: 'કેશ સમરી પાનાં નં.', fieldType: 'TEXT_SHORT', sequence: 8 },
        { code: 'FLD_IM_RESPONSIBLE_STAFF', labelEn: 'Responsible employee name', labelGu: 'જવાબદાર કર્મચારીનું નામ', fieldType: 'TEXT_SHORT', sequence: 9 },
        { code: 'FLD_IM_SILAK_HANDOVER_SIGN', labelEn: 'Signature of person presenting & receiving back silak', labelGu: 'સિલ્વિક રજૂ કરનાર તથા પરત મેળવનારની સહી', fieldType: 'SIGNATURE', sequence: 10 },
        { code: 'FLD_IM_WITHIN_LIMIT', labelEn: 'Silak within limit?', labelGu: 'સિલ્વિક મર્યાદામાં રહે છે કે કેમ ? (હા / ના)', fieldType: 'RADIO_YN', sequence: 11 },
        { code: 'FLD_IM_SURPRISE_CHECK', labelEn: 'Monthly surprise silak check by Branch Manager done & reported? (dates)', labelGu: 'બ્રાન્ચ મેનેજર દ્વારા દર માસે સરપ્રાઈઝ સિલ્વિક ચેક થયાનું તપાસો. રિપોર્ટ થાય છે કે કેમ ? (તા.)', fieldType: 'TEXT_LONG', sequence: 12 },
        { code: 'FLD_IM_RECENT_SILAK_REPORT', labelEn: 'If silak inspected recently, check report', labelGu: 'નજીકની તારીખમાં સિલ્વિક તપાસેલ હોય તો રિપોર્ટ તપાસવા', fieldType: 'RADIO_YN', sequence: 13 },
        { code: 'FLD_IM_NOTE_MACHINE', labelEn: 'Note counting machine working? Displayed for customers? Running?', labelGu: 'નોટ કાઉન્ટીંગ મશીન બરાબર ચાલે છે કે નહીં ? ગ્રાહકો જોઈ શકે તે રીતે ડિસ્પ્લે રાખેલ છે કે નહીં ? ચાલુ છે કે નહીં જોવું', fieldType: 'RADIO_YN', sequence: 14 },
        { code: 'FLD_IM_CCTV_CUSTODY', labelEn: 'Received payment seals & cash summary kept in custody verified via CCTV; both officers together after placing cash', labelGu: 'રિસીવ્ડ પેમેન્ટના સિક્કા તથા કેશ સમરી કસ્ટડીમાં રાખવામાં આવ્યાનું સી.સી.ટી.વી. ફૂટેજથી તપાસવું. બંને હોદ્દારોની કેશ મૂક્યા બાદ સાથે જ', fieldType: 'RADIO_YN', sequence: 15 },
        { code: 'FLD_IM_SAFE_LOCK_PROCEDURE', labelEn: 'Observe privately procedure of locking safe by ringing key; give necessary instructions', labelGu: 'ચાવી વગાવી તિજોરી બંધ કરવાની ગતિ વિધિ ખાનગીમાં જોવી. તથા જરૂરી સૂચના આપવી', fieldType: 'RADIO_YN', sequence: 16 },
        { code: 'FLD_IM_NOTICE_BOARD_RBI', labelEn: 'Notice board as per RBI instructions?', labelGu: 'નોટિશ બોર્ડ પર આરબીઆઈની સૂચના મુજબ છે કે નહીં તે તપાસવું', fieldType: 'RADIO_YN', sequence: 17 },
      ],
    },
    {
      code: 'SEC_IM_CASH_SUMMARY_SIGN',
      titleEn: 'Account Dept - (2) Cash Summary, Scroll, Vouchers & Keys',
      titleGu: 'એકાઉન્ટ વિભાગ - (૨) કેશ સમરી, સ્ક્રોલ, રોજમેળ, વાઉચર તથા ચાવી',
      sequence: 3,
      fields: [
        { code: 'FLD_IM_SUMMARY_SIGN', labelEn: 'Responsible persons signatures as per sample on cash summary, scroll, daily book vouchers regular? Computer reports signed?', labelGu: 'કેશ સમરી, કેશ સ્ક્રોલ, રોજમેળ વાઉચારોમાં જવાબદારોની નમૂના મુજબની સહીઓ નિયમિત થાય છે કે કેમ ? સૂચ્યા મુજબના કોમ્પ્યુટર રિપોર્ટ તપાસી સહીઓ થયેલ છે કે કેમ ?', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_FEE_REGISTER', labelEn: 'Fee register time-date-name written; regular charge settlement signed?', labelGu: 'ફી રજિસ્ટરમાં સમય-તારીખ અને નામ લખવામાં આવે છે જે તપાસવું તેમજ નિયમિત ચાર્જની વેવડ-ટેવડ કરી સહીઓ થાય છે કે કેમ ?', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_DUPLICATE_KEYS', labelEn: 'Duplicate keys kept in which branch; rotated periodically? Last key change date', labelGu: 'ડુપ્લિકેટ ચાવીઓ કઈ શાખામાં રખાયેલ છે તેની વિગત તપાસવી. સમયાંતરે રોટેશન થાય છે કે નહીં તે તપાસવું. છેલ્લે ચાવી બદલેલ તારીખ લખવી (હા/ના, તા.)', fieldType: 'TEXT_LONG', sequence: 3 },
      ],
    },
    {
      code: 'SEC_IM_OTHER_BANK_BAL',
      titleEn: 'Account Dept - (3) Other Banks Balances & Reconciliation',
      titleGu: 'એકાઉન્ટ વિભાગ - (૩) અન્ય બેંકોના બેલેન્સ અંગે તથા બેલેન્સ મેળવણા',
      sequence: 4,
      fields: [
        { code: 'FLD_IM_BAL_CERT_DATE', labelEn: 'Last balance certificate obtained date (monthly)', labelGu: 'બેલેન્સ સર્ટિફિકેટ છેલ્લું મેળવ્યાની તારીખ (મંથલી મેળવવું)', fieldType: 'DATE', sequence: 1 },
        { code: 'FLD_IM_PENDING_ENTRIES', labelEn: 'Responsible officer obtained pending entries, verified & signed; long-pending entries checked', labelGu: 'જવાબદાર અધિકારીએ પેન્ડિંગ એન્ટ્રી મેળવી તપાસી વેરીફાઈ કરી સહી કરવી. લાંબા સમયની પેન્ડિંગ એન્ટ્રી તપાસવી', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_STMT_TESTCHECK', labelEn: 'Test-check cash transactions in statement of accounts; verify officer signature specimens', labelGu: 'સ્ટેટમેન્ટ ઓફ એકાઉન્ટના ખાતાઓમાં રોકડ વ્યવહારો ટેસ્ટ ચેકસમા તપાસવા. અધિકારીની સહીના નમૂના તપાસવા', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_RECON_PENDING', labelEn: 'Reconciliation sheet: entries pending >1 month details; check correspondence & give instructions', labelGu: 'મેળવણા પત્રકમાં ૧-માસથી વધારે સમયની પેન્ડિંગ એન્ટ્રીની વિગત આપવી તથા થયેલ પત્ર વ્યવહાર તપાસી જરૂરી સૂચનો કરવા', fieldType: 'TEXT_LONG', sequence: 4 },
      ],
    },
    {
      code: 'SEC_IM_ACCOUNT_OPENING',
      titleEn: 'Account Dept - (4) New Account Opening Forms & Documents',
      titleGu: 'એકાઉન્ટ વિભાગ - (૪) નવા એકાઉન્ટ ઓપનિંગ ફોર્મ તથા આધારો અંગે',
      sequence: 5,
      fields: [
        { code: 'FLD_IM_OPENING_FORMS', labelEn: 'Current/savings/fixed account opening forms & nominee appointment documents examined', labelGu: 'ચાલુ / બચત / બાંધી મુદત ખાતા ઓપનિંગ ફોર્મ તથા વારસદારની નિમાણૂકના આધારો તપાસી જણાવો', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_CLOSED_ACCOUNTS', labelEn: 'Record of accounts closed during year checked', labelGu: 'વર્ષ દરમ્યાન બંધ થયેલ ખાતાનો રેકર્ડ તપાસવો', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_KYC', labelEn: 'KYC form obtained & verified against original docs with signatures; implementation; documents uploaded in computer (random check)', labelGu: 'કે.વાય.સી. ફોર્મ મેળવ્યાનું તથા અસલ ડોક્યુમેન્ટ સાથે ખરાઈ કરી સહીઓ થાય છે કે કેમ ? તેની અમલવારી તપાસવી અને મેળવેલ ડોક્યુમેન્ટસજ કોમ્પ્યુટરમાં ચડાવેલ છે કે કેમ ? તે રેન્ડમલી તપાસવું', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_CPC_FORMS', labelEn: 'Account opening forms opened by CPC checked', labelGu: 'CPC દ્વારા ખોલવામાં આવેલ એકાઉન્ટ ઓપનિંગ ફોર્મ તપાસવા', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_IM_CHEQUE_BOOK_REG', labelEn: 'Cheque book issue register: numbered bag for ornaments; register check; numbered stationery stock on inspection date; sign after check; cheque/FD/DD issue pending?', labelGu: 'ચેક બુક ઇશ્યુ રજિસ્ટર : દાગીના રાખવાની નંબરવાળી થેલી રહે છે કેમ ? જે રજિસ્ટર મુજબ ચેક થાય છે? નંબરોગવાળી તમામ સ્ટેશનરીનો સ્ટોક તપાસણીની તારીખે મળે છે કે કેમ ? તપાસ્યા બદલની સહી કરવી. ચેક બુક, ફી. ડી., ડી.ડી. આપવાની બાકી નથી ને ? તે અંગે તપાસવું', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_IM_RISK_FORM_SIGN', labelEn: 'Signature verified in risk form? Fraud checked serially', labelGu: 'રિસ્કિશન ફોર્મમાં સહી વેરીફાઈ થાય છે? ફ્રાઉડિંગ ક્રમશ: થયાનું તપાસવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_CHEQUE_RETURN_CHARGE', labelEn: 'Cheque return charges recovered regularly', labelGu: 'ચેક રિટર્ન ચાર્જ નિયમસર વસૂલ થયાનું તપાસવું', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_IM_STAFF_FD', labelEn: 'Staff FD declarations obtained & filed date-wise; senior citizen FD documents checked', labelGu: 'સ્ટાફ ફી.ડી.ના ડેક્લેરેશન મેળવી તારીખ વાઈઝ ફાઈલે રાખવા / સિનિયર સીટીઝન ફી.ડી.ના આધારો તપાસવા', fieldType: 'RADIO_YN', sequence: 8 },
        { code: 'FLD_IM_DEAD_STOCK_REG', labelEn: 'Dead stock entered in register; items in good condition; register regular; new dead stock/furniture in proper use; regular disposal of condemnable dead stock', labelGu: 'ફર્નિચર : ડેડ સ્ટોક ધરાવો રજિસ્ટરમાં નોંધેલ છે તે તપાસવું; ડેડ સ્ટોકની આઈટમો સારી સ્થિતિમાં છે કે કેમ ? રજિસ્ટર નિયમિત લખાયેલ છે કે કેમ ? નવા મંગાવેલ ડેડ સ્ટોક / ફર્નિચર યોગ્ય રીતે વપરાશમાં રાખેલ છે કે નહીં ? રદ પાત્ર ડેડ સ્ટોકનો નિયમસર નિકાલ કરવા તપાસી જણાવવું', fieldType: 'RADIO_YN', sequence: 9 },
        { code: 'FLD_IM_SUNDRY_PENDING', labelEn: 'Sundry debtors/debitors/suspense or other pending entries details; correspondence with HO; HO approval for sundry/suspense transactions; excess silak in sundry debtors intimated to HO & return approval', labelGu: 'બીજી પરચૂરણ રકમો : સન્દ્રીડેટર્સ / ડેબિટર્સ / સસપેન્સ કે અન્ય પેન્ડિંગ એન્ટ્રીઓની વિગત આપવી તથા હેડ ઓફિસ સાથેનો પત્ર વ્યવહાર તપાસવો; તેમજ સન્દ્રીડિટર્સ/ડેટર્સ / સસપેન્સમાં કરેલ વ્યવહાર અંગે હે.ઓ.ની મંજૂરી મેળવેલ છે કે નહીં તે તપાસવું; સન્દ્રી ડેબિટર્સમાં સિલ્વિક વધારાની રકમ જમા વેવાયેલ હોય તેની હેડ ઓફિસને જાણ તપાસવું અને પરત કરવાની થાય તો મંજૂરી મેળવેલ છે કે કેમ તપાસવું', fieldType: 'TEXT_LONG', sequence: 10 },
      ],
    },
    {
      code: 'SEC_IM_COMPUTER_MAINT',
      titleEn: '(5) Computer Maintenance',
      titleGu: '(૫) કોમ્પ્યુટર જાળવણી',
      sequence: 6,
      fields: [
        { code: 'FLD_IM_EQUIPMENT_MAINT', labelEn: 'CCTV cameras, security system, computers, printers, battery, UPS, passbook printer, note counting machine etc. cleaning/maintenance proper?', labelGu: 'સી.સી.ટી.વી. કેમેરા, સિક્યોરીટી સિસ્ટમ, કોમ્પ્યુટર, પ્રિન્ટર્સ, બેટરી, યુ.પી.એસ., પાસબુક પ્રિન્ટર, નોટ કાઉન્ટિંગ મશીન વિગેરેની સાફ સફાઈ જાળવણી યોગ્ય રીતે થાય છે?', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_STATIONERY_WASTE', labelEn: 'Computer stationery shortage/wastage not happening?', labelGu: 'કોમ્પ્યુટર સ્ટેશનરીનો ખૂટો બચાડ થતો નથી ને ? તે તપાસવું', fieldType: 'RADIO_YN', sequence: 2 },
      ],
    },
    {
      code: 'SEC_IM_STAFF_WORK',
      titleEn: '(6) Employee Work & Attendance',
      titleGu: '(૬) કર્મચારીની કામગીરી અંગે',
      sequence: 7,
      fields: [
        { code: 'FLD_IM_ATTENDANCE_LEAVE', labelEn: 'Employee attendance sheet & leave register checked; leave report entered; leave as per rules; working days checked', labelGu: 'કર્મચારી હાજરી પત્રક તથા રજા રજિસ્ટર તપાસવું. રજા રિપોર્ટ ઇનવર્ડ વેવાયેલ છે ? રજાના નિયમો મુજબ જ રજાની અમલવારી થાય છે તે તપાસો. કામના દિવસો ચેક કરવા', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_WORK_ROTATION', labelEn: 'Work allocation & rotation system adopted?', labelGu: 'કામગીરીની ફાળવણી તથા રોટેશન પદ્ધતિ અપનાવેલ છે કે કેમ ? તપાસવું', fieldType: 'RADIO_YN', sequence: 2 },
      ],
    },
    {
      code: 'SEC_IM_LOCKERS',
      titleEn: '(7) Lockers',
      titleGu: '(૭) લોકર અંગે',
      sequence: 8,
      fields: [
        { code: 'FLD_IM_VACANT_LOCKERS', labelEn: 'Vacant lockers since when; action to give on rent & guidance; state details in report', labelGu: 'શાખામાં ખાલી ખાના કેટલા સમયથી છે, તેમજ ભાડે અપાય તે માટે જરૂરી ચર્યા કરી માર્ગદર્શન આપવું રિપોર્ટમાં વિગતે જણાવવું', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_IM_LOCKER_KEYBOOK', labelEn: 'Key-book register checked; locker operating system observed privately; done by custodian?', labelGu: 'લે-બુક રજિસ્ટર તપાસવું. લોકર ઓપરેટિંગ સિસ્ટમ ખાનગી રાહે જોવી. કસ્ટોડિયન દ્વારા જ થાય છે કે નહીં તે જોવું', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_LOCKER_AGREEMENT', labelEn: 'Locker agreements checked', labelGu: 'લોકર એગ્રીમેન્ટની તપાસ કરવી', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_LOCKER_CBS', labelEn: 'Locker opening entries made in CBS?', labelGu: 'લોકર ઓપનિંગ અંગેની CBS માં એન્ટ્રી કરવામાં આવે છે કે નહીં તે તપાસવું', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_IM_LOCKER_BREAKOPEN', labelEn: 'Locker break-open cases checked', labelGu: 'લોકર બ્રેક-ઓપન કેસ તપાસવા', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_IM_LOCKER_ITEMS_RENT', labelEn: 'Register of items found in locker & sent to HO; locker rent not due?', labelGu: 'લોકરમાં મળેલ વસ્તુની યાદી રજિસ્ટર તથા હેડ ઓફિસને મોકલ્યા અંગે. લોકર ભાડું ડ્યુ નથી ને ? તે તપાસવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_LOCKER_RENTED_DOCS', labelEn: 'Documents of lockers given on rent during inspection period checked', labelGu: 'ઇન્સ્પેક્શન પિરિયડમાં ભાડે અપાયેલ લોકરના દસ્તાવેજો તપાસવા', fieldType: 'RADIO_YN', sequence: 7 },
      ],
    },
    {
      code: 'SEC_IM_REMITTANCE',
      titleEn: '(8) Remittances',
      titleGu: '(૮) રેમિટન્સ અંગે',
      sequence: 9,
      fields: [
        { code: 'FLD_IM_ATM_SILAK', labelEn: 'If ATM: silak within limit; remittance register entries; officers checked', labelGu: 'એ.ટી.એમ હોય તો તેમાંની સિલ્વિક મર્યાદામાં તપાસવી તેમજ રેમિટન્સ રજિસ્ટરમાં નોંધ થયાનું તપાસવું તેમજ અધિકારો તપાસવા', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_REMIT_REG_SIGN', labelEn: 'Remittance receipt-payment register notes & signatures at respective times; responsible officer signature as per sample; scroll entries only after remittance presented', labelGu: 'રેમિટન્સ લેવડ-દેવડના રજિસ્ટરમાં જરૂરી નોંધ તેમજ સહીઓ જે તે સમયે થયાનું તપાસવું. જવાબદાર અધિકારીની નમૂના મુજબની સહી થયાનું તપાસવું. સ્ક્રોલમાં નોંધ રેમિટન્સ રજૂ થયા પછી જ કરેલી હોવી જોઈએ', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_REMIT_CONFIDENTIAL', labelEn: 'Confidentiality maintained while depositing/receiving remittance? Action & guidance', labelGu: 'રેમિટન્સ ભરવા-લેવા જતી વખતે ગોપનિયતા (ખાનગીપણું) જળવાય છે કે કેમ ? તે અંગે ચર્યા કરી સમજણ આપવી', fieldType: 'RADIO_YN', sequence: 3 },
      ],
    },
    {
      code: 'SEC_IM_DAYBOOK_VOUCHERS',
      titleEn: '(9) Day Book & Vouchers',
      titleGu: '(૯) ડે-બુક તથા વાઉચારો તપાસવા',
      sequence: 10,
      fields: [
        { code: 'FLD_IM_VOUCHER_BINDING', labelEn: 'Voucher binding with voucher numbers & regular signatures of cashier-account-branch manager', labelGu: 'વાઉચર બંધન ઉપર વાઉચર નંબરો તથા કેશિયર-એકાઉન્ટ-બ્રાંચ મેનેજરની નિયમિત સહી થયાનું તપાસવું', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_VOUCHERS_AUDIT_PERIOD', labelEn: 'Audit period debit/credit vouchers with references; cash rectification report & register; VVR report verified daily with voucher', labelGu: 'ઓડિટ પિરિયડના જમા / ઉધાર વાઉચરો સન્દર્ભિમન્દ્રી સાથે તપાસવા. કેશ રેક્ટિફિકેશન રિપોર્ટ તથા રજિસ્ટર તપાસવા અને વી. વી. આર. રિપોર્ટ વાઉચર સાથે દરરોજ વેરીફાઇ થાય છે તે તપાસવું', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_JOINT_SIGN', labelEn: 'Joint signatures of cashier & account/branch manager to customer counter by duplicating? Observe cashier debit-credit vouchers/transactions', labelGu: 'જમા સહીઓમાં કેશિયર તથા એકાઉન્ટ / બ્રાંચ મેનેજર બે ની સંયુક્ત સહીઓ ગ્રાહકના કાઉન્ટરના દુરૂપિયાત કરી આપાય છે કે કેમ? તે તપાસો. કેશિયરના જમા-ઉધાર વાઉચરો / વ્યવહારોનું નિરીક્ષણ કરવું', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_DEBIT_VOUCHER_SIGN', labelEn: 'Debit vouchers: posting person sign, cheque passer sign, cashier sign in stamp, payer sign at back; illiterate holder cheques & payment system; denomination written; large cheques BM counter signature before payment', labelGu: 'ઉધાર વાઉચરો ચાલુ બચતના ચેકોનું પોસ્ટિંગ કરનારની સહી ચેક પાસ કરનારની સહી પેઠેના સિક્કામાં કેશિયરની સહી વાઉચર / ચેક પાછળ નાણાં ચેનારની સહી થયાનું તપાસો. અભાણ ધારણદારોના ચેક તેમજ પેમેન્ટ સિસ્ટમ તપાસવી. ડીનોમિનેશન લખાયેલ છે કે નહીં મોટી રકમના ચેક પેમેન્ટ કરતાં પહેલા બ્રાંચ મેનેજરની કાઉન્ટર સહી લેવા પ્રથા રાખસો', fieldType: 'RADIO_YN', sequence: 4 },
      ],
    },
    {
      code: 'SEC_IM_EXPENSES',
      titleEn: 'Expense Vouchers & Bills',
      titleGu: 'ખર્ચના વાઉચરો તથા બિલો',
      sequence: 11,
      fields: [
        { code: 'FLD_IM_EXPENSE_VOUCHERS', labelEn: 'Expense vouchers checked; entries in expense register; expense as per authority; light/telephone bill, house tax, rent, profession tax etc. paid after BM verification; late charge paid? If yes reasons', labelGu: 'ખર્ચના વાઉચરો તપાસવા ખર્ચ રજિસ્ટરમાં નોંધ કર્યાનું તપાસવું. મળેલ અધિકાર મુજબ જ ખર્ચ થયાનું તપાસવું. લાઈટ બિલ, ટેલિફોન બિલ, મકાન વેરો, મકાન ભાડા, શાખા વ્યવસાય વેરો વિગેરે બિલોમાં બ્રાંચ મેનેજરે ખરાઈ કર્યા બાદ ચૂકવાય છે કે કેમ ? તે તપાસવું વેઇટ ચાર્જ ભરાયેલ છે ? જો હા તો કારણો જણાવો', fieldType: 'RADIO_YN', sequence: 1 },
      ],
    },
    {
      code: 'SEC_IM_SUCCESSOR',
      titleEn: '(10) Successor / Deceased Cases',
      titleGu: '(૧૦) વારસદારના કિસ્સા',
      sequence: 12,
      fields: [
        { code: 'FLD_IM_SUCCESSOR_DOCS', labelEn: 'Successor cases: paid current/savings/fixed deposits - branch authority & HO approval, application & documents obtained regularly; prescribed BM share? Action & guidance', labelGu: 'વારસદારના કિસ્સામાં ચૂકવેલ ચાલુ બચત, બાંધી મુદત થાપણો અંગે શાખાને મળેલ અધિકાર તથા હે.ઓ. મંજૂરીથી ચૂકવેલ થાપણોની અરજી તથા આનુસાંગિક આધારો નિયમસર મેળવ્યાનું તપાસવું. તેમજ નિયત બ્રાંચ મેનેજરના શેરા છે કે કેમ ? તે અંગે જરૂરી ચર્યા કરી માર્ગદર્શન આપવું', fieldType: 'RADIO_YN', sequence: 1 },
      ],
    },
    {
      code: 'SEC_IM_DUPLICATE_FD',
      titleEn: '(11) Duplicate FD',
      titleGu: '(૧૧) ુપ્લિકેટ ફી.ડી.',
      sequence: 13,
      fields: [
        { code: 'FLD_IM_DUP_FD_DETAILS', labelEn: 'Duplicate FDs issued as per branch authority: check details; guidance', labelGu: 'શાખાને મળેલ અધિકાર પ્રમાણે ઇશ્યુ કરેલ ડુપ્લિકેટ ફી.ડી.ની વિગતો તપાસી લેવી. જરૂરી માર્ગદર્શન આપવું', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_DUP_FD_NOT_ENCASHED', labelEn: 'In duplicate FD cases, specially check FD not previously encashed', labelGu: 'ડુપ્લિકેટ ફી.ડી. ના કેસ માં આ ફી.ડી. અગાઉ વટાવી નાખેલ નથી ને તે ખાસ તપાસવું', fieldType: 'RADIO_YN', sequence: 2 },
      ],
    },
    {
      code: 'SEC_IM_TARGETS',
      titleEn: '(12) Branch Targets',
      titleGu: '(૧૨) શાખાના લક્ષ્યાંકો',
      sequence: 14,
      fields: [
        { code: 'FLD_IM_TARGETS', labelEn: 'Check targets allotted to branch (account numbers, deposits, medium-term credit) & targets given by HO', labelGu: 'શાખાને ફાળવેલ લક્ષ્યાંકો જેવા કે ખાતા સંખ્યા, ડિપોઝિટ, મ.મુ. ધિરાણો તથા હેડ ઓફિસ તરફથી અપાયેલ લક્ષ્યાંકો તપાસવા', fieldType: 'TEXT_LONG', sequence: 1 },
      ],
    },
    {
      code: 'SEC_IM_REPORTS',
      titleEn: '(13) Reports & Interest Rates',
      titleGu: '(૧૩) રિપોર્ટ તથા વ્યાજદર',
      sequence: 15,
      fields: [
        { code: 'FLD_IM_REPORTS_CHECK', labelEn: 'Supplementary, non-home branch cash report printed, checked, signed-stamped? Other necessary reports checked? CC/OD loan report interest rates on computer; supplementary checked by BM', labelGu: 'સપ્લીમેન્ટ્રી, નોન હોમ બ્રાંચ કેશ રિપોર્ટ પ્રિન્ટ કાઢી તપાસી સહી-સિક્કા થાય છે ? તેમજ અન્ય જરૂરી રિપોર્ટ તપાસાય છે ? તે જોવું સી.સી., ઓ.ડી. લોન રિપોર્ટ કોમ્પ્યુટર પર વ્યાજના દરો તપાસવા. તેમજ સપ્લીમેન્ટ્રી બ્રાંચ મેનેજરે તપાસવાની છે', fieldType: 'RADIO_YN', sequence: 1 },
      ],
    },
    {
      code: 'SEC_IM_RECTIFICATION',
      titleEn: '(14) Inspection Rectification Follow-up',
      titleGu: '(૧૪) ઇન્સ્પેક્શન દુરસ્તી ફોલો-અપ',
      sequence: 16,
      fields: [
        { code: 'FLD_IM_LAST_RECT_REPORT', labelEn: 'Check last rectification reports of internal & vigilance inspection; verify actual rectification; separate note of pending points or mention in report; review sheets demanded under internal inspection & give suggestions', labelGu: 'ઇન્સ્પેક્શન મુજબના ઇન્ટરનલ ઇન્સ્પેક્શન, વિજિલન્સ ઇન્સ્પેક્શનના છેલ્લા દુરસ્તી રિપોર્ટ તપાસી વાસ્તવિક દુરસ્તી થયાની ખરાઈ કરી બાકી રહેલ મુદ્દાઓની અલગ નોંધ આપવી કે રિપોર્ટમાં ઉલ્લેખ કરવો. તેમજ આંતરિક ઇન્સ્પેક્શન અન્વયે માંગવામાં આવેલ પત્રક તપાસી તેની સમીક્ષા અને સૂચનો રિપોર્ટમાં કરવા', fieldType: 'TEXT_LONG', sequence: 1 },
      ],
    },
    {
      code: 'SEC_IM_REGISTERS',
      titleEn: '(15) Accounts Dept Registers - Completeness',
      titleGu: '(૧૫) એકાઉન્ટસ વિભાગે રાખેલ રજિસ્ટરો તપાસી અપૂર્ણતા અંગે જણાવો',
      sequence: 17,
      fields: [
        {
          code: 'FLD_IM_REGISTERS_GRID', labelEn: 'Accounts Dept Registers', labelGu: 'એકાઉન્ટસ વિભાગના રજિસ્ટરો', fieldType: 'GRID', sequence: 1,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'ક્રમ', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_REGISTER', labelEn: 'Register', labelGu: 'રજિસ્ટર', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_COMPLETE', labelEn: 'Complete / Remarks', labelGu: 'અપૂર્ણતા / રિમાર્ક', columnType: 'TEXT_LONG', sequence: 3 },
          ],
          seedRows: [
            { sr: 1, register: 'ફી રજિસ્ટર', complete: '' },
            { sr: 2, register: 'રેમિટન્સ રજિસ્ટર', complete: '' },
            { sr: 3, register: 'કેશ સમરી', complete: '' },
            { sr: 4, register: 'કેશ સ્ક્રોલ', complete: '' },
            { sr: 5, register: 'ચેક રિટર્ન રજિસ્ટર', complete: '' },
            { sr: 6, register: 'ડેડ સ્ટોક રજિસ્ટર', complete: '' },
            { sr: 7, register: 'સ્ટેશનરી રજિસ્ટર', complete: '' },
            { sr: 8, register: 'લોકર કી રજિસ્ટર', complete: '' },
            { sr: 9, register: 'લોકર ઓપરેટ રજિસ્ટર', complete: '' },
            { sr: 10, register: 'તાર ટપાલ રજિસ્ટર / આંગડિયા રજિસ્ટર', complete: '' },
            { sr: 11, register: 'રજા રજિસ્ટર', complete: '' },
            { sr: 12, register: 'સ્ટેઇવ ડી.ડી. રજિસ્ટર', complete: '' },
            { sr: 13, register: 'મળેલ પેકેટ અંગેનું કસ્ટડી રજિસ્ટર', complete: '' },
            { sr: 14, register: 'ડી.ઇ.એ.એફ. ફાઇલ (DEAF)', complete: '' },
            { sr: 15, register: 'સી.સી.ટી.વી. સિક્યોરીટી રજિસ્ટર', complete: '' },
            { sr: 16, register: 'લોકર બ્રેક ઓપન રજિસ્ટર', complete: '' },
            { sr: 17, register: 'શાખાનું રેકર્ડ બહાર વર્ગ જવાનું રજિસ્ટર', complete: '' },
            { sr: 18, register: 'પાસવર્ડ રજિસ્ટર', complete: '' },
            { sr: 19, register: 'એ.ટી.એમ. કાર્ડ રજિસ્ટર', complete: '' },
            { sr: 20, register: 'મોબાઈલ બેન્કિંગ રજિસ્ટર', complete: '' },
          ],
        },
      ],
    },
    {
      code: 'SEC_IM_LOAN_GOLD',
      titleEn: 'Loan Dept - (1) Credit against Gold Ornaments',
      titleGu: 'લોન વિભાગ - (૧) સોના દાગીના સામે ધિરાણ અંગે',
      sequence: 18,
      fields: [
        { code: 'FLD_IM_GOLD_DOCS_KYC', labelEn: 'Gold ornament credit documents register & KYC checked', labelGu: 'સોના દાગીના સામે ધિરાણના દસ્તાવેજો રજિસ્ટર, કે.વાય.સી. તપાસવા', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_GOLD_INTEREST_TERM', labelEn: 'Interest rate at account opening, individual interest & term checked', labelGu: 'ખાતા ખોલતા સમયે નાખેલ વ્યાજદર, ઇંડનીવ વ્યાજ તથા મુદત તપાસવા', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_GOLD_PRINCIPAL_OS', labelEn: 'Principal o/s count & amount; over-3-month principal o/s count & amount', labelGu: 'મુ.વી. બાકી સંખ્યા / રકમ રૂ. ; ત્રણ માસ ઉપરનું મુ.વી. સંખ્યા / રકમ રૂ.', fieldType: 'TEXT_LONG', sequence: 3 },
        { code: 'FLD_IM_GOLD_PACKETS', labelEn: 'Number of seal-closed gold ornament packets', labelGu: 'સોના દાગીના સીલ બંધ પેકેટસ સંખ્યા', fieldType: 'NUMBER', sequence: 4 },
        { code: 'FLD_IM_GOLD_HANDOVER_SIGN', labelEn: 'Signatures of presenter & receiver (manager A/c cashier)', labelGu: 'રજૂ કરનાર અને પરત મેળવનારની સહીઓ મેનેજર એકા / કેશિયર', fieldType: 'SIGNATURE', sequence: 5 },
        { code: 'FLD_IM_JOINT_CUSTODY', labelEn: 'Implementation as per joint custody circular checked; action & guidance', labelGu: 'જોઈન્ટ કસ્ટડી પરિપત્ર મુજબનો અમલ થયાનું તપાસો જરૂરી ચર્યા કરી માર્ગદર્શન આપવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_GOLD_STORAGE', labelEn: 'Where gold ornament packets & seals kept; details', labelGu: 'સોના દાગીના પેકેટસ તથા સીલ ક્યા રાખવામાં આવે છે. તેની વિગત', fieldType: 'TEXT_LONG', sequence: 7 },
        { code: 'FLD_IM_GOLD_TESTING', labelEn: 'On visit day at credit: cut & touchstone + nitric acid test done? Stone & acid with valuer? Silver seal etc. checked', labelGu: 'મુલાકાતના દિવસે ધિરાણ સમયે કાનસ મારી તથા કસોટી પથ્થર ઉપર ઘસીને નાઈટ્રિક એસિડથી ચકાસણી થાય છે કે કેમ ? ધિરાણ સમયે પથ્થર તથા એસિડ વેલ્યુઅર પાસે છે કે કેમ ? રૂપરૂ સીલ વિગેરે તપાસવા', fieldType: 'RADIO_YN', sequence: 8 },
        { code: 'FLD_IM_VALUER_DOCS', labelEn: 'Valuer mortgage documents as per credit limit & HO limit; cases above individual limit; reliever valuer profile card; if >1 valuer, intimation letter & profile cards obtained?', labelGu: 'વેલ્યુઅરના જમીનગીરીના દસ્તાવેજો ધિરાણ લિમિટ મુજબના મેળવ્યાનું તપાસો તથા હેડ ઓફિસ મંજૂરીની લિમિટ તપાસી. વ્યક્તિગત મર્યાદાથી વધુ ધિરાણના કિસ્સા તપાસવા. રિલિવર વેલ્યુઅરનું પ્રોફાઇલ કાર્ડ તપાસવું. શાખામાં એક કરતાં વધારે વેલ્યુઅર હોય તો જમીનગીરી જે શાખામાં છે તે શાખાએ અન્ય શાખાને જાણ કરતો પત્ર પ્રોફાઇલ કાર્ડ, રિલિવર વેલ્યુઅરનું પ્રોફાઇલ કાર્ડ મેળવેલ છે કે કેમ ? તપાસવું', fieldType: 'RADIO_YN', sequence: 9 },
        { code: 'FLD_IM_GOLD_PACKET_RETURN', labelEn: 'Ornament packet not returned despite credit repaid: details; received after year-end (30-June)? Custody charge recovered & amount', labelGu: 'દાગીના ધિરાણ ચૂકતે થતા છતાં ચાલમાં આપેલ દાગીનાનું પેકેટ પરત મેળવેલ ન હોય તેની વિગતો તપાસવી. આવા પેકેટ વર્ષાંતે (૩૦-જૂન) પછી રિસિવ થયેલ છે કે નહીં ? તેની વિગતો તપાસવી. તે પેકેટ દેની સમયે કસ્ટડી ચાર્જ વસુલવાનુ તપાસવું અને વસુલ રકમ લખવી', fieldType: 'TEXT_LONG', sequence: 10 },
        { code: 'FLD_IM_GOLD_PANCH_VERIFY', labelEn: 'Gold ornament packets verification (panch) date & number; serious defect found - write', labelGu: 'સોના દાગીના પેકેટસ પંચક્ષ્યાસ કર્યા તારીખ, સંખ્યા; પંચક્ષ્યાસ સમયે ગંભીર ક્ષતિ માલૂમ પડેલ હોય તો તે લખો', fieldType: 'TEXT_LONG', sequence: 11 },
      ],
    },
    {
      code: 'SEC_IM_LOAN_FD',
      titleEn: 'Loan Dept - (2) Loan / OD against FD',
      titleGu: 'લોન વિભાગ - (૨) ફી.ડી. સામે લોન : ફિક્સીંગ સામે લોન ફી. ડી. સામે ઓવરડ્રાફ્ટ – વ્યક્તિ – મંડળી',
      sequence: 19,
      fields: [
        { code: 'FLD_IM_FD_OD_ACCOUNTS', labelEn: 'FD-OD accounts of societies/individuals: interest rate, term, interest calculation; new account statements check rate/limit keep with loan kits; accounts repaid during inspection period checked', labelGu: 'ફી. ડી. સામે ઓવરડ્રાફ્ટ મંડળીઓને/ વ્યક્તિઓના ખાતા તપાસવા, વ્યાજ દર, મુદત તથા ખાતા ઉભા હોય તેની વ્યાજ ગણતરી ચેક કરવી. તેમજ નવા ખૂલતાં ખાતાના સ્ટેટમેન્ટ કાઢી વ્યાજદર,લિમિટ વિગેરે તપાસી લોન કેટ્સ સાથે રાખવા તેમજ ઇન્સ્પેક્શન પિરિયડ વખતે ચૂકતે થયેલ ખાતા તપાસવા', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_FD_MARGIN', labelEn: 'Documents obtained as per rules maintaining prescribed margin', labelGu: 'દસ્તાવેજો નિયમ મુજબ નિયત માર્જિન જાળવી મેળવ્યાનું તપાસો', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_FD_SECURITY_REG', labelEn: 'FD receipts reconciled in security register', labelGu: 'સિક્યોરીટી રજિસ્ટરમાં ફી. ડી. રસીદોનું મેળવણું કરવું', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_FD_LIEN_SIGN', labelEn: 'FD receipts lien in bank treasury & signature verified', labelGu: 'ફી. ડી. રસીદો બેંકની ટ્રેજરમાં વિયન થયાનું તથા સિગ્નેચર વેરીફાઈ થયાનું તપાસો', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_IM_FD_ACK', labelEn: 'Acknowledgement issued to depositor for FD receipt currently received', labelGu: 'થાપણદારને ફી. ડી. રસીદ હાલમાં મળ્યાની પહોંચ ઇશ્યુ કર્યાનું તપાસો', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_IM_OD_AFTER_TERM', labelEn: 'No transactions in current overdraft account after term expiry?', labelGu: 'કરંટ ઓવર ડ્રાફ્ટ ખાતાની મુદત પૂર્ણ થયાં બાદ ટ્રાન્ઝેક્શન કરવામાં આવે છે નહિ ? તપાસવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_MINOR_DECL', labelEn: 'In minor cases declaration obtained', labelGu: 'સગીર કિસ્સામાં ડેક્લેરેશન મેળવ્યાનું તપાસવું', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_IM_OVERDUE_RECEIPTS', labelEn: 'No overdue debit receipts; loan amount recovered at maturity', labelGu: 'રધુ ડેબિટની રસીદો નથી ને ? તે તપાસી પાકતી મુદતે લોનની રકમ વસુલ મેળવ્યાનું તપાસવું', fieldType: 'RADIO_YN', sequence: 8 },
        { code: 'FLD_IM_AUTHORITY_LETTER', labelEn: 'Authority letter obtained to credit amount to loan account on maturity date', labelGu: 'પાકતી તારીખે રકમ લોન ખાતે જમા કરવાનો ઓથોરીટી લેટર મેળવ્યાનું તપાસો', fieldType: 'RADIO_YN', sequence: 9 },
      ],
    },
    {
      code: 'SEC_IM_LOAN_KCC',
      titleEn: 'Loan Dept - (3) KCC Credit & KCC Mortgage / via Society',
      titleGu: 'લોન વિભાગ - (૩) કે.સી.સી. ધીરણો તથા કે.સી.સી. નામજોગ / મંડળી મારફત',
      sequence: 20,
      fields: [
        { code: 'FLD_IM_KCC_SAVINGS', labelEn: 'KCC withdrawal credited only to borrower savings account? No other-purpose withdrawal; if so check & report separately', labelGu: 'કે.સી.સી. ધીરણોનો ઉપાડ ધિરાણ લેનારના બચત ખાતે જ જમા આપીને આપેલ છે ? અન્ય હેતુ માટે ઉપાડ આપી શકાય નહિ. જો હોય તો તપાસી અલગથી રિપોર્ટ કરવો', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_KCC_CONDITIONS_BREACH', labelEn: 'KCC sanction conditions violated (e.g. 106(1) papers): inspection rectification report obtained?', labelGu: 'કે.સી.સી. મંજૂરી પત્રની શરતોનો ભંગ થયેલ હોય તો જેવી કે ૧૦૬ (૧) ના કાગળો તપાસણી દુરસ્તી રિપોર્ટ મેળવેલ છે કે કેમ ?', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_KCC_ABOVE_3L', labelEn: 'Interest rate checked in credits above 3 lakh; statement printed', labelGu: '3 લાખ ઉપરના ધીરણોમાં વ્યાજદર તપાસવો. સ્ટેટમેન્ટ કઢાવવું', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_KCC_CARD_RECOVERY', labelEn: 'KCC card & sanction sheets with member-wise recovery checked', labelGu: 'કે.સી.સી. કાર્ડ, મંજૂર થયાના પત્રકો જેમાં સભ્ય વાઈઝ વસૂલાત આવેલ છે કે કેમ ? તે તપાસવું', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_IM_KCC_MORTGAGE_DOCS', labelEn: 'Mortgage KCC credit documents checked; renewal obtained', labelGu: 'નામજોગ કે.સી.સી. ધિરાણુના દસ્તાવેજો વિગેરે તપાસવા. તેની બહાલી મેળવેલ છે તે તપાસવું', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_IM_KCC_LIMIT', labelEn: 'No excess withdrawal/outstanding over bank total sanctioned KCC limit', labelGu: 'બેંકની કુલ મંજૂર કે.સી.સી. લિમિટથી વધુ ઉપાડ / બાકી નથી ને તપાસવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_SUSPENSE_UNPOSTED', labelEn: 'On credit to suspense, no amounts to unposted accounts? If so interest issue checked', labelGu: 'સસ્પેન્સ એકાઉન્ટમાં જમા થયાં ત્યારે સાથે અનપોસ્ટેડ ખાતામાં રકમો ગયેલ નથી ને ? જો હોય તો વ્યાજનો પ્રશ્ન થાય તે તપાસવું', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_IM_KCC_SOCIETY_AGREEMENT', labelEn: 'Society doing KCC credit submitted agreement & 7/12 and 8-A land extract copies at branch & filed?', labelGu: 'કેસીસી ધિરાણ કરતી મંડળીએ એકરારનામાં માં તથા ૭/૧૨ અને ૮ અની જમીનના ઉતારાની નકલ શાખામાં રજૂ કરેલ છે અને તે શાખાની ફાઈલે છે કે નહીં તે તપાસવું', fieldType: 'RADIO_YN', sequence: 8 },
      ],
    },
    {
      code: 'SEC_IM_LOAN_MEDIUM',
      titleEn: 'Loan Dept - (4) Medium Term Credit - via Society',
      titleGu: 'લોન વિભાગ - (૪) મધ્યમ મુદત ધીરણો – મંડળી મારફત',
      sequence: 21,
      fields: [
        { code: 'FLD_IM_MT_ASSET_VERIFY', labelEn: 'Asset verification done in medium term credit?', labelGu: 'મધ્યમ મુદત ધીરણોમાં એસેટ વેરિફિકેશન કરેલ છે કે કેમ ?', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_MT_DISBURSE_DOCS', labelEn: 'Disbursement sheets assigned & obtained; running-type credit accompanying documents (HPA, TTO, bill-reach insurance etc.) checked', labelGu: 'ચૂકવણા પત્રકો એસાઈન થઈ મેળવેલ છે કે કેમ ? સભ્યને ચાલન પ્રકારના કરેલ ધિરાણના આનુસંગિક આધારો મેળવ્યા છે કે કેમ ? એચ.પી.એ., ટી.ટી.ઓ., બીલ-પહોંચ વીમો વિગેરે આધારો તપાસવા', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_MT_NONVEHICLE_CERT', labelEn: 'For non-vehicle credit, society certificate given?', labelGu: 'વાહનો સિવાયના ધીરાણમાં મંડળીએ પ્રમાણપત્ર આપેલ છે કે કેમ ? તપાસવું', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_MT_DOCS_COMPLETE', labelEn: 'Medium term credit documents checked; certificate of documents-complete sent ensured', labelGu: 'મધ્યમ મુદત ધીરણોમાં દસ્તાવેજો તપાસી, દસ્તાવેજો પૂર્ણ હોવાનું પ્રમાણપત્ર મોકલ્યા ખાતરી કરવી', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_IM_MT_SANCTION_BREACH', labelEn: 'Sanction conditions of medium term / ro.sha. violated - state', labelGu: 'મ. મુ./રો.શા. મંજૂરી પત્રની શરતોનો ભંગ થયેલ હોય તો જણાવો', fieldType: 'TEXT_LONG', sequence: 5 },
        { code: 'FLD_IM_MT_STOCK_SILAK', labelEn: 'At document submission: society previous-day summary-stock sheet; silak fully filled & verified?', labelGu: 'દસ્તાવેજો રજૂ થતી વખતે મંડળીનું આગલા દિવસનું સરવૈયું –સ્ટોક પત્રક લઈ સિલ્વિક પૂરી ભરાઈ છે કે કેમ ? તેમજ ચકાસવામાં આવેલ છે કે કેમ ? તે જોવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_ASSIGNMENT_RECOVERY', labelEn: 'Society/bank assignment receivables details & recovery action; recovery amount during internal inspection', labelGu: 'શાખા તણેની ફરિયા મંડળી / બેંક અસાઈમેન્ટ લેણાની વિગત તેમજ વસૂલાત માટે થયેલ કાર્યવાહીની વિગત જણાવો આંતરિક ઇન્સ્પેક્શન સમય દરમ્યાન આવેલ વસૂલાતની રકમ લખો', fieldType: 'TEXT_LONG', sequence: 7 },
      ],
    },
    {
      code: 'SEC_IM_SOCILITIES',
      titleEn: 'Loan Dept - (5) Societies under Branch',
      titleGu: 'લોન વિભાગ - (૫) શાખા નીચેની મંડળીઓ અંગે',
      sequence: 22,
      fields: [
        { code: 'FLD_IM_SOC_MONTHLY_SHEETS', labelEn: 'Societies monthly sheets submitted regularly, entered & shared; cash credit margin break stated; 1 imbalance bank loan vs society summary - report to loan dept, subsidy o/s? 2 no non-routine transactions on sheet date 3 pending assistance entry - written instruction 4 group-wise balance & verification report from monthly sheet, error letter written', labelGu: 'મંડળીઓના માસિક પત્રકો નિયમિત રજુથાય છે કે કેમ ? ઇનવર્ડ કરી જરૂરી વિગતે શેરા થાય છે કે કેમ ? કેશ ક્રેડિટ માર્જિન તૂટ હોય તો જણાવો. ૧. બેંક લોન બાકી અને મંડળીના સરવૈયા મુજબની સભ્ય બાકી વચ્ચે ઇમબેલેંસ હોય તો અલગથી લોન વિભાગને રિપોર્ટ કરવો. સબસીડીની બાકી મળે છે કે કેમ? ૨. માસિક પત્રકની તારીખમાં રૂટિન સિવાયના ખાતામાં જેવા કે કાયમી બંડોળોમાં ટ્રાન્ઝેક્શન થયેલ નથીને ? 3. બેંક કે સરકારશ્રી તરફથી ચૂકવવામાં આવેલ કોઈપણ સહાયની રકમની એન્ટ્રી પેન્ડિંગ હોય તો લેખિત સૂચના આપવી ૪. મંડળીના બેંક લોન ખાતાના ગ્રુપવાઈઝ બેલેન્સ કાઢી તેમજ માસિક પત્રક પરથી ચકાસણી રિપોર્ટ ભરાયેલ છે ? તેમજ ક્ષતિ અંગેનો પત્ર લખવામાં આવે છે', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_IM_SOC_SHARE_DEPOSIT', labelEn: 'Borrowing members credit shares & deposits filled; matched with defaulter sheet & shared; signatures; implementation as per circular', labelGu: 'મંડળીઓના ધિરાણ લેતા સભાસદોના ધિરાણ શેર, થાપણની ભરાઈ થયેલ છે કે કેમ ? બાકીદારના પત્રક સાથે મેળવાય છે શેરા થયેલ છે ? સહીઓ થાય છે ને ? પરિપત્ર મુજબ અમલવારી તપાસવી', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_SOC_INSURANCE', labelEn: 'Societies silak/goods stock insurance taken on time & renewed timely', labelGu: 'મંડળીઓના સિલ્વિક / માલ સ્ટોકના વિમાઓ મુદતસર લેવાયેલ છે કે કેમ ? સમયસર રિન્યુ થયાનું તપાસો', fieldType: 'RADIO_YN', sequence: 3 },
        {
          code: 'FLD_IM_SOC_PROP_CARDS_GRID', labelEn: 'Society Property Cards (check once in Q4)', labelGu: 'મંડળીના મિલકત પત્રકોની વિગત (ચોથા ક્વાર્ટરમાં એક વખત તપાસવું)', fieldType: 'GRID', sequence: 4,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'ક્રમ', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_SOC_COUNT', labelEn: 'No. of Societies', labelGu: 'મંડળીની સંખ્યા', columnType: 'NUMBER', sequence: 2 },
            { code: 'COL_PROP_OBTAINED', labelEn: 'Societies with property card obtained', labelGu: 'મેળવેલ મિલકત પત્રકની મંડળી સંખ્યા', columnType: 'NUMBER', sequence: 3 },
            { code: 'COL_PROP_PENDING', labelEn: 'Societies with property card pending', labelGu: 'બાકી મિલકત પત્રકવાળી મંડળીની સંખ્યા', columnType: 'NUMBER', sequence: 4 },
            { code: 'COL_GRAM_SEVED', labelEn: 'Gram Sevak verified & shared (Y/N)', labelGu: 'ગ્રા.મે તપાસી શેરો કરેલ છે હા / ના', columnType: 'TEXT_SHORT', sequence: 5 },
            { code: 'COL_REMARKS', labelEn: 'Remarks', labelGu: 'રિમાર્કસ', columnType: 'TEXT_LONG', sequence: 6 },
          ],
        },
      ],
    },
    {
      code: 'SEC_IM_IRREGULARITY',
      titleEn: 'Loan Dept - (6) Irregularity, Administration, Scam',
      titleGu: 'લોન વિભાગ - (૬) ગેરરીતિ, વહીવટ, ગોટાળા અંગે',
      sequence: 23,
      fields: [
        { code: 'FLD_IM_IRREG_DETAIL', labelEn: 'Irregularity, scam or mismanagement during branch inspection - state in detail', labelGu: 'શાખાના ઇન્સ્પેક્શન સમયમાં ગેરરીતિ, ગોટાળા કે ગેરવહીવટ હોય તો વિગતે જણાવો', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_IM_PUNISHED_STAFF', labelEn: 'Work of employee involved in misappropriation/punished checked; charge matter as per HO instruction; check privately', labelGu: 'ઉચાપત કે સજા પામેલ કર્મચારીની કામગીરી તપાસવી. હે.ઓ. ની સૂચના મુજબ ચાર્જ બાબતે તપાસવું. ખાનગીમાં વાઈડ સ્ટાઈલ તપાસવી', fieldType: 'TEXT_LONG', sequence: 2 },
        { code: 'FLD_IM_THEFT_ROBBERY', labelEn: 'Theft, robbery or other incidents at branch - state in detail', labelGu: 'શાખામાં ચોરી, લૂંટ કે અન્ય બનાવો બનેલ હોય તો વિગતે જણાવો', fieldType: 'TEXT_LONG', sequence: 3 },
        { code: 'FLD_IM_RULE_VIOLATION', labelEn: 'Violation of rules in duty - state in detail', labelGu: 'ફરજમાં નિયમોનું ઉલ્લંઘન થયેલ હોય તો વિગતે જણાવો', fieldType: 'TEXT_LONG', sequence: 4 },
      ],
    },
    {
      code: 'SEC_IM_STAFF_LOANS',
      titleEn: 'Loan Dept - (7) Staff Credits',
      titleGu: 'લોન વિભાગ - (૭) સ્ટાફના ધીરણો',
      sequence: 24,
      fields: [
        { code: 'FLD_IM_STAFF_LOAN_TERMS', labelEn: 'Loan against NSC/FD/GOVT.SEC/insurance policy: maturity date, margin, interest rate checked', labelGu: 'એન.એસ.સી. / ફી.ડી. /GOVT.SEC/ વિમા પોલિસી સામે લોન પાકતી તારીખ તથા માર્જિન, વ્યાજદર તપાસવો', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_STAFF_LOAN_DOCS', labelEn: 'Category-wise loan documents verified regularly', labelGu: 'નિયમસર લોનના પ્રકારવાર મેળવેલ દસ્તાવેજોની ખરાઈ કરવી', fieldType: 'RADIO_YN', sequence: 2 },
      ],
    },
    {
      code: 'SEC_IM_MT_NONAGRI',
      titleEn: 'Loan Dept - (8) Medium Term Non-Agri & Mortgage Credit',
      titleGu: 'લોન વિભાગ - (૮) મ.મુ. બિનખેતી તથા નામ જોગ ધિરાણ',
      sequence: 25,
      fields: [
        { code: 'FLD_IM_TITLE_DOCS', labelEn: 'Title report & mortgage documents; for non-agri via society & parallel-mortgage credits: copies of title report docs, index, mortgage deed, purchase docs, revenue record, property card, insurance etc.; check with equitable mortgage deed; originals obtained', labelGu: 'ટાઈટલ રિપોર્ટ તથા જમીનગીરીમાં મેળવેલ દસ્તાવેજો નામજોગ ધીરણોમાં મંડળી મારફતના બિન ખેતી ધીરણો સમાંતર જમીનગીરી લેવામાં આવેલ ધીરણોમાં ટાઈટલ રિપોર્ટ સાથેના દસ્તાવેજો, ઈંડ, મોર્ગેજ ડિડ, ખરીદ દસ્તાવેજોની નકલ, રેવન્યુ, રેકર્ડ, પ્રોપર્ટી, કાર્ડ, વીમો વિગેરે તકલો લેવી. ઈક્વિટેબલ મોર્ટેજ ડિડ સાથે તપાસવા. અસલ દસ્તાવેજો મેળવેલ હોવા જોઈએ', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_IM_MORTGAGE_RELEASE', labelEn: 'After loan repaid, equitable mortgage cancelled & file returned to original owner?', labelGu: 'લોન ચૂકતે થયા બાદ ઈક્વિટેબલ મોર્ગેજ રદ કરવી ફાઈલ મૂળ મલીકને પરત સોંપેલ છે કે નહિ તે વિગત તપાસવી', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_IM_ADVANCE_CHEQUE_VALUATION', labelEn: 'Advance cheque, acknowledgement & bills - site verification & valuation report; signatures of BM / society secretary / customer in value report', labelGu: 'એડવાન્સ ચેક તથા તેનું કબૂલતનામું તથા બિલો – સ્થળ ખરાઈ તથા વેલ્યુએશન રિપોર્ટ તપાસવા. વેલ્યૂ રિપોર્ટમાં બ્રાન્ચ મેનેજર / મંડળીના મંત્રી / ગ્રાહકની સહીઓ જોવી', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_IM_ABOVE_10L_FAIR_VALUE', labelEn: 'Loan above 10.00 lakh: fair valuation of parallel mortgage property by concerned officer?', labelGu: '૧૦.૦૦ લાખથી વધુ અપાયેલ લોન કેસમાં સમાંતર જમીનગીરી મિલકતનું ફેર વેલ્યુએશન લગત અધિકારી દ્વારા થયેલ છે કે કેમ? તપાસવું', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_IM_STOCK_DRAWING_POWER', labelEn: 'Applicable cases: stock sheet, drawing power register checked; verification report filled by BM & enclosed?', labelGu: 'લાગુ પડતાં કેઈસમાં સ્ટોક પત્રક ડ્રોઈંગ પાવર રજિસ્ટર તપાસવા તથા વેરિફિકેશન રિપોર્ટ બ્રાન્ચ મેનેજર ભરીને સામેલ રાખેલ છે કે કેમ ?', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_IM_LOAN_ASSET_VERIFY', labelEn: 'Asset verification of property purchased via loan done', labelGu: 'લોન દ્વારા ખરીદેલ મિલકતનું એસેટવેરિફિકેશન થયાનું તપાસવું', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_IM_AD_REGISTER_NOTICE', labelEn: 'Borrower & land owner informed from A.D. register? Action on returned notices? Check & state', labelGu: 'ધિરાણ લેનાર તથા જમીન ધનાર એ. ડી. રજિસ્ટર થી જાણ કરવામાં આવે છે કે કે નહિ ? પરત આવેલ નોટિસની ફરે કાર્યવાહી થાય છે કે કેમ ? તપાસી જણાવો', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_IM_NPA_RECOVERY', labelEn: 'Principal-o/s loan cases: recovery action correspondence checked & guidance; NPA accounts checked; write branch recovery action details', labelGu: 'મુ. વિ થયેલ લોન કેસમાં વસૂલાતની થયેલ કાર્યવાહી પત્ર વ્યવહાર તપાસી જવા જરૂરી માર્ગદર્શન સૂચનો કરવા તથા એન. પી. એ. થયેલ ખાતા તપાસવા અને વસૂલાત અંગે શાખાએ કરેલ કાર્યવાહીની વિગત લખવી', fieldType: 'TEXT_LONG', sequence: 8 },
        { code: 'FLD_IM_INSURANCE_REGISTER', labelEn: 'Match mortgage credit account numbers with computer insurance register; insurance amount not taken - get it taken', labelGu: 'નામજોગ ધિરાણોની ખાતા સંખ્યા સાથે કોમ્પ્યુટરમાં વીમા રજિસ્ટરમાં તે પ્રકારના ખાતા સંખ્યાની ચકાસણી કરી વીમા રકમ લેવડાવેલ ન હોય તે ખાતાઓના લેવડાવડા', fieldType: 'RADIO_YN', sequence: 9 },
      ],
    },
    {
      code: 'SEC_IM_SIGNOFF',
      titleEn: 'Sign-off',
      titleGu: 'સહી',
      sequence: 26,
      fields: [
        { code: 'FLD_IM_PLACE', labelEn: 'Place', labelGu: 'મુકામ', fieldType: 'TEXT_SHORT', sequence: 1 },
        { code: 'FLD_IM_DATE', labelEn: 'Date', labelGu: 'તારીખ', fieldType: 'DATE', sequence: 2 },
        { code: 'FLD_IM_SIGN_NAME', labelEn: 'Name (Signature)', labelGu: 'નામ (સહી)', fieldType: 'TEXT_SHORT', sequence: 3 },
        { code: 'FLD_IM_SIGN_DESG', labelEn: 'Designation', labelGu: 'હોદ્દો', fieldType: 'TEXT_SHORT', sequence: 4 },
        { code: 'FLD_IM_AUDITOR_SIGNATURE', labelEn: 'Inspecting Officer Signature', labelGu: 'ઇન્સ્પેક્શન અધિકારીની સહી', fieldType: 'SIGNATURE', isMandatory: true, sequence: 5 },
      ],
    },
  ];

  template.sections = sections;
  await template.save();

  const AuditType = require('../models/AuditType');
  await AuditType.findByIdAndUpdate(auditType._id, { currentTemplateId: template._id });

  return template;
};
