const Template = require('../models/Template');

module.exports = async function createMandaliDaftarTemplate(auditType) {
  const template = await Template.create({
    auditType: auditType._id,
    version: 1,
    status: 'Published',
    publishedAt: new Date(),
    sections: [],
  });

  const sections = [
    {
      code: 'SEC_MD_HEADER',
      titleEn: 'Society & Inspection Header',
      titleGu: 'મંડળી અને તપાસણી હેડર માહિતી',
      sequence: 1,
      fields: [
        { code: 'FLD_MD_YADI_DATE', labelEn: 'Daftar Tapasani Yadi Date', labelGu: 'દફ્તર તપાસણી યાદીની તારીખ', fieldType: 'DATE', isMandatory: true, sequence: 1 },
        { code: 'FLD_MD_SOC_NAME', labelEn: 'Society Name (Current)', labelGu: 'મંડળીનું નામ (હાલનું)', fieldType: 'TEXT_SHORT', isMandatory: true, sequence: 2 },
        { code: 'FLD_MD_SOC_NAME_PREV', labelEn: 'Society Name (Previous)', labelGu: 'મંડળીનું નામ (અગાઉનું)', fieldType: 'TEXT_SHORT', sequence: 3 },
        { code: 'FLD_MD_WORK_VILLAGE', labelEn: 'Working Centre Village', labelGu: 'કાર્ય મથકનું ગામ', fieldType: 'TEXT_SHORT', sequence: 4 },
        { code: 'FLD_MD_TALUKA', labelEn: 'Taluka', labelGu: 'તાલુકો', fieldType: 'TEXT_SHORT', sequence: 5 },
        { code: 'FLD_MD_AREA_VILLAGES', labelEn: 'Villages in Work Area', labelGu: 'કાર્યક્ષેત્રના ગામના નામ', fieldType: 'TEXT_LONG', sequence: 6 },
        { code: 'FLD_MD_REPORT_SEND_DATE', labelEn: 'Date of Sending Report', labelGu: 'કુ. રિપોર્ટ મોકલવાની તારીખ', fieldType: 'DATE', sequence: 7 },
        { code: 'FLD_MD_INSPECTION_FROM', labelEn: 'Inspection Period From', labelGu: 'તપાસણીનો સમય તા.', fieldType: 'DATE', sequence: 8 },
        { code: 'FLD_MD_INSPECTION_TO', labelEn: 'Inspection Period To', labelGu: 'થી તા. સુધી', fieldType: 'DATE', sequence: 9 },
        { code: 'FLD_MD_OFFICER_NAME', labelEn: 'Inspecting Officer Name', labelGu: 'તપાસણી કરનાર અધિકારીનું નામ', fieldType: 'TEXT_SHORT', sequence: 10 },
        { code: 'FLD_MD_OFFICER_DESG', labelEn: 'Designation', labelGu: 'હોદ્દો', fieldType: 'TEXT_SHORT', sequence: 11 },
        { code: 'FLD_MD_REG_NO', labelEn: 'Registration Number', labelGu: 'નોંધણીનો નંબર', fieldType: 'TEXT_SHORT', sequence: 12 },
        { code: 'FLD_MD_REG_DATE', labelEn: 'Registration Date', labelGu: 'નોંધણીની તારીખ', fieldType: 'DATE', sequence: 13 },
        { code: 'FLD_MD_LAST_YEAR_PL', labelEn: 'Last Year Profit / Loss', labelGu: 'ગત વર્ષનો નફો / ખોટ', fieldType: 'CURRENCY', sequence: 14 },
        { code: 'FLD_MD_LAST_AUDIT_DETAIL', labelEn: 'Last Audit Details', labelGu: 'છેલ્લી ઓડિટની વિગત', fieldType: 'TEXT_LONG', sequence: 15 },
        { code: 'FLD_MD_AUDIT_PERIOD', labelEn: 'Audit Period (From - To)', labelGu: 'ઓડિટ સમય તા. થી તા. સુધી', fieldType: 'TEXT_SHORT', sequence: 16 },
        { code: 'FLD_MD_AUDIT_CLASS', labelEn: 'Audit Class & Date', labelGu: 'વર્ગ : તારીખ :', fieldType: 'TEXT_SHORT', sequence: 17 },
        { code: 'FLD_MD_RECT_REPORT_DATE', labelEn: 'Rectification Report Sent Date', labelGu: 'દુરસ્તી રિપોર્ટ મોકલવાની તારીખ', fieldType: 'DATE', sequence: 18 },
      ],
    },
    {
      code: 'SEC_MD_STOCK_SILAK',
      titleEn: 'Last Stock & Silak Inspection',
      titleGu: 'મંડળીનો છેલ્લો સ્ટોક તથા સિલક તપાસચાની વિગત',
      sequence: 2,
      fields: [
        {
          code: 'FLD_MD_STOCK_SILAK_GRID', labelEn: 'Last Stock & Silak Verification', labelGu: 'છેલ્લો સ્ટોક તથા સિલક તપાસચાની વિગત', fieldType: 'GRID', sequence: 1,
          gridColumns: [
            { code: 'COL_DETAIL', labelEn: 'Detail', labelGu: 'વિગત', columnType: 'TEXT_SHORT', sequence: 1 },
            { code: 'COL_DATE', labelEn: 'Date', labelGu: 'તારીખ', columnType: 'DATE', sequence: 2 },
            { code: 'COL_REMARKS', labelEn: 'Remarks', labelGu: 'રિમાર્કસ', columnType: 'TEXT_LONG', sequence: 3 },
          ],
          seedRows: [
            { detail: 'માલ સ્ટોક', date: '', remarks: '' },
            { detail: 'સિલક', date: '', remarks: '' },
          ],
        },
        { code: 'FLD_MD_PROP_CARD_DATE', labelEn: 'Property Card Verification Date', labelGu: 'મિલકત પત્રકની ચકાસણીની તપાસચાની તારીખ', fieldType: 'DATE', sequence: 2 },
        { code: 'FLD_MD_PROP_OFFICER', labelEn: 'Verifying Officer Name', labelGu: 'ચકાસણી કરનાર અધિકારીનું નામ', fieldType: 'TEXT_SHORT', sequence: 3 },
        { code: 'FLD_MD_PROP_OFFICER_DESG', labelEn: 'Verifying Officer Designation', labelGu: 'ચકાસણી કરનાર અધિકારીનો હોદ્દો', fieldType: 'TEXT_SHORT', sequence: 4 },
      ],
    },
    {
      code: 'SEC_MD_MEMBERS',
      titleEn: 'Members & Borrowing Members',
      titleGu: 'મંડળીની સભ્ય સંખ્યા તથા કર્જ લેતા સભ્યોની માહિતી',
      sequence: 3,
      fields: [
        {
          code: 'FLD_MD_MEMBER_GRID', labelEn: 'Member & Farmer Account Holders', labelGu: 'સભ્ય તથા ખાતેદાર ખેડૂતોની સંખ્યા', fieldType: 'GRID', sequence: 1,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'અ.નં.', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_DETAIL', labelEn: 'Detail', labelGu: 'વિગત', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_SMALL_FARMER', labelEn: 'Small Farmers', labelGu: 'નાના ખેડૂત', columnType: 'NUMBER', sequence: 3 },
            { code: 'COL_OTHER_FARMER', labelEn: 'Other Farmers', labelGu: 'અન્ય ખેડૂત', columnType: 'NUMBER', sequence: 4 },
            { code: 'COL_OUTSTANDING', labelEn: 'Outstanding', labelGu: 'ઉભક', columnType: 'NUMBER', sequence: 5 },
            { code: 'COL_TOTAL', labelEn: 'Total', labelGu: 'કુલ', columnType: 'NUMBER', sequence: 6 },
          ],
          seedRows: [
            { sr: 1, detail: 'કુલ ખાતેદારો', smallFarmer: '', otherFarmer: '', outstanding: '', total: '' },
            { sr: 2, detail: 'તે પૈકી મંડળીમાં સભ્યો', smallFarmer: '', otherFarmer: '', outstanding: '', total: '' },
            { sr: 3, detail: 'તે પૈકી કર્જ લેતા સભ્યો', smallFarmer: '', otherFarmer: '', outstanding: '', total: '' },
            { sr: 4, detail: 'તે પૈકી બાકી સભ્યો', smallFarmer: '', otherFarmer: '', outstanding: '', total: '' },
            { sr: 5, detail: 'તે પૈકી મુ.વિ. બાકીદારો', smallFarmer: '', otherFarmer: '', outstanding: '', total: '' },
          ],
        },
        { code: 'FLD_MD_SEPARATE_OFFICE', labelEn: 'Separate & Independent Office?', labelGu: 'હા અલગ અને સ્વતંત્ર ઓફીસ છે ? ના', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_MD_EXT_BORROW_LIMIT', labelEn: 'External Borrowing Limit as per Bye-laws (Rs.)', labelGu: 'પેટા નિયમ મુજબ બહારથી કર્જની હદ (રૂ.)', fieldType: 'CURRENCY', sequence: 3 },
        { code: 'FLD_MD_OUTSTANDING_STMT', labelEn: 'Statement of outstanding from members (date-wise) attached', labelGu: 'તારોજ સભાસદો પાસે બાકી લેણાંની વિગતનું પત્રક / સામેલ નમુના મુજબ મેળવીને મોકલ્યું ?', fieldType: 'RADIO_YN', sequence: 4 },
      ],
    },
    {
      code: 'SEC_MD_LOANS_RECOVERY',
      titleEn: 'Loans Obtained & Recovery',
      titleGu: 'મંડળીએ મેળવેલ લોન, ભરપાઈ કરેલ વસુલાત અને બાકીની માહિતી',
      sequence: 4,
      fields: [
        { code: 'FLD_MD_LOAN_STMT', labelEn: 'Loan / recovery / outstanding statement attached as per sample', labelGu: 'મંડળીએ મેળવેલ લોન, ભરપાઈ કરેલ વસુલાત અને બાકીની માહિતીનું પત્રક / સામેલ નમુના મુજબ મેળવીને મોકલ્યું ?', fieldType: 'RADIO_YN', sequence: 1 },
        {
          code: 'FLD_MD_ANNUAL_RECOVERY_GRID', labelEn: 'Last Year Annual Recovery as on 30-06', labelGu: 'તા. ૩૦-૦૬ ની સ્થિતિએ ગત વર્ષની વાર્ષિક વસુલાતની માહિતી', fieldType: 'GRID', sequence: 2,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'ક્રમ', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_LOAN_TYPE', labelEn: 'Loan Type', labelGu: 'લોનનો પ્રકાર', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_DEMAND_CURRENT', labelEn: 'Demand Current', labelGu: 'વાર્ષિક ડીમાન્ડ ચાલુ', columnType: 'CURRENCY', sequence: 3 },
            { code: 'COL_DEMAND_PRIN', labelEn: 'Demand Principal O/s', labelGu: 'વાર્ષિક ડીમાન્ડ મુ.વિ.', columnType: 'CURRENCY', sequence: 4 },
            { code: 'COL_DEMAND_TOTAL', labelEn: 'Demand Total', labelGu: 'વાર્ષિક ડીમાન્ડ કુલ', columnType: 'CURRENCY', sequence: 5 },
            { code: 'COL_RECOV_CURRENT', labelEn: 'Recovery Current', labelGu: 'વાર્ષિક વસુલાત ચાલુ', columnType: 'CURRENCY', sequence: 6 },
            { code: 'COL_RECOV_PRIN', labelEn: 'Recovery Principal', labelGu: 'વાર્ષિક વસુલાત મુ.વિ.', columnType: 'CURRENCY', sequence: 7 },
            { code: 'COL_RECOV_TOTAL', labelEn: 'Recovery Total', labelGu: 'વાર્ષિક વસુલાત કુલ', columnType: 'CURRENCY', sequence: 8 },
            { code: 'COL_PCT_CURRENT', labelEn: 'Recovery % Current', labelGu: 'વસુલાતના ટકા ચાલુ', columnType: 'PERCENTAGE', sequence: 9 },
            { code: 'COL_PCT_PRIN', labelEn: 'Recovery % Principal', labelGu: 'વસુલાતના ટકા મુ.વિ.', columnType: 'PERCENTAGE', sequence: 10 },
            { code: 'COL_PCT_TOTAL', labelEn: 'Recovery % Total', labelGu: 'વસુલાતના ટકા કુલ', columnType: 'PERCENTAGE', sequence: 11 },
          ],
        },
        { code: 'FLD_MD_RECOVERY_SHEET', labelEn: 'Recovery info from 01-07 to inspection date attached (separate sheet)', labelGu: 'તા. ૧-૭ થી તપાસણી તારીખ સુધીની વસુલાતની માહિતી (નમુનો પાછળ) મુજબ અલગ પત્રક બીડ્યું ?', fieldType: 'RADIO_YN', sequence: 3 },
      ],
    },
    {
      code: 'SEC_MD_SHARE_CAPITAL',
      titleEn: 'Share Capital & Share Purchase',
      titleGu: 'શેર ભંડોળ અને શેર ખરીદી અંગે',
      sequence: 5,
      fields: [
        {
          code: 'FLD_MD_SHARE_CAPITAL_GRID', labelEn: 'Authorised & Paid-up Share Capital', labelGu: 'અધિકૃત અને ભરપાઈ થયેલ શેર ભંડોળ', fieldType: 'GRID', sequence: 1,
          gridColumns: [
            { code: 'COL_HEAD', labelEn: 'Head', labelGu: '', columnType: 'TEXT_SHORT', sequence: 1 },
            { code: 'COL_AUTHORISED', labelEn: 'Authorised (Rs.)', labelGu: 'અધિકૃત શેર ભંડોળ રકમ રૂ.', columnType: 'CURRENCY', sequence: 2 },
            { code: 'COL_PAID_CREDIT', labelEn: 'Paid-up Credit', labelGu: 'ભરપાઈ થયેલ જમા', columnType: 'CURRENCY', sequence: 3 },
            { code: 'COL_PAID_DEBIT', labelEn: 'Paid-up Debit', labelGu: 'ભરપાઈ થયેલ ઉધાર', columnType: 'CURRENCY', sequence: 4 },
            { code: 'COL_PAID_BAL', labelEn: 'Paid-up Balance', labelGu: 'ભરપાઈ થયેલ બાકી', columnType: 'CURRENCY', sequence: 5 },
          ],
          seedRows: [
            { head: 'સભ્યોનું', authorised: '', paidCredit: '', paidDebit: '', paidBal: '' },
            { head: 'સરકારશ્રીનું', authorised: '', paidCredit: '', paidDebit: '', paidBal: '' },
            { head: 'કુલ', authorised: '', paidCredit: '', paidDebit: '', paidBal: '' },
          ],
        },
        { code: 'FLD_MD_AUTH_VS_PAID', labelEn: 'Authorised share capital vs paid-up as per bye-laws', labelGu: 'પેટા નિયમ મુજબ અધિકૃત શેર ભંડોળ તથા તે સામે ભરપાઈ થયેલું શેર ભંડોળ જણાવો', fieldType: 'TEXT_LONG', sequence: 2 },
        { code: 'FLD_MD_NEW_MEMBER_SHARE', labelEn: 'Members admitted during inspection: application, entry fee & share entered as per rules?', labelGu: 'તપાસણી સમય દરમિયાન દાખલ કરેલ સભ્યોની સભાસદ અરજી પ્રવેશફી તથા શેરની રકમ લઈ શેરની નિયમસર દાખલ કરેલ છે કે કેમ ? તેની વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 3 },
        {
          code: 'FLD_MD_MEMBER_MOVEMENT_GRID', labelEn: 'Member Movement', labelGu: 'સભ્ય સંખ્યાની હિલચાલ', fieldType: 'GRID', sequence: 4,
          gridColumns: [
            { code: 'COL_SMALL', labelEn: 'Small Farmers', labelGu: 'નાના ખેડૂત', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_OTHER', labelEn: 'Other Farmers', labelGu: 'અન્ય ખેડૂત', columnType: 'NUMBER', sequence: 2 },
            { code: 'COL_OUTSTANDING', labelEn: 'Outstanding', labelGu: 'ઉભક', columnType: 'NUMBER', sequence: 3 },
            { code: 'COL_TOTAL', labelEn: 'Total', labelGu: 'કુલ', columnType: 'NUMBER', sequence: 4 },
          ],
          seedRows: [
            { small: '', other: '', outstanding: '', total: '' },
          ],
        },
        { code: 'FLD_MD_MEMBER_COUNTS', labelEn: 'Members: (a) at year start (b) new during year (c) left during year (d) at year end', labelGu: 'અ. વર્ષની શરૂઆતમાં સભ્ય સંખ્યા / બ. વર્ષ દરમ્યાન નવા દાખલ થયેલા સભ્યો / ક. વર્ષ દરમ્યાન છૂટા થયેલ / ડ. વર્ષ આખરે બાકી', fieldType: 'TEXT_LONG', sequence: 5 },
        { code: 'FLD_MD_SHARE_LIMIT_EXCEED', labelEn: 'If share capital exceeds bye-law limit, arrangement to amend bye-laws', labelGu: 'શેર ભંડોળ પેટા નિયમની મર્યાદાથી વધુ હોય તો પેટા નિયમ સુધારવા કરેલ વ્યવસ્થાની વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 6 },
        { code: 'FLD_MD_SHARE_CERT', labelEn: 'Share certificate issued to every member? Unissued arranged & entered in share register?', labelGu: 'પ્રત્યેક સભાસદોને શેર સર્ટિફિકેટ આપવામાં આવેલ છે કે કેમ ? ન અપાયેલ સર્ટિફિકેટ અંગે ઘટતી વ્યવસ્થા કરાવો તથા શેર રજિસ્ટરમાં તેની યોગ્ય રીતે નોંધ થયેલ છે કે કેમ તે જણાવો', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_MD_GOV_SHARE', labelEn: 'Govt shareholding: outstanding payable installments, installment-wise amount & payment date; register checked', labelGu: 'સરકારશ્રીની શેર ભાગીદારી હોય તો તે પૈકી ભરવાપાત્ર ચકત હપ્તા બાકી હોય તો હપ્તાવાર રકમ અને તેની ભરપાઈ કરવાની તારીખ જણાવો અને આ અંગેનું રજિસ્ટર તપાસો', fieldType: 'TEXT_LONG', sequence: 8 },
        { code: 'FLD_MD_PROFIT_LOSS_DIV', labelEn: 'Accumulated profit/loss, last year profit/loss, dividend %, dividend on govt share & date sent; profit distribution as per bye-laws?', labelGu: 'મંડળીનો એકત્રિત નફો / એકત્રિત ખોટ હોય તો જણાવો તેમજ મંડળીએ ગત વર્ષ કરેલ નફો / ખોટ જણાવો તથા ડીવિડન્ડ બાહેર કરેલ હોય તો તેના ટકા અને સરકારશ્રીના શેર ફાળા ઉપર ડીવિડન્ડની રકમ અને મોકલી આપ્યાની તારીખ જણાવો અને નફાની ફાળવણી પેટા નિયમ મુજબ થયેલ છે કે કેમ તે જણાવો', fieldType: 'TEXT_LONG', sequence: 9 },
      ],
    },
    {
      code: 'SEC_MD_SHARES_PURCHASED',
      titleEn: 'Shares Purchased by Society',
      titleGu: 'મંડળીએ ખરીદેલ શેર અંગેની માહિતી',
      sequence: 6,
      fields: [
        {
          code: 'FLD_MD_SHARES_PURCH_GRID', labelEn: 'Shares Purchased Register', labelGu: 'મંડળીએ ખરીદેલ શેર અંગેની માહિતી', fieldType: 'GRID', sequence: 1,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'અ.નં.', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_INST_NAME', labelEn: 'Institution Name', labelGu: 'સંસ્થાનું નામ', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_SHARE_TYPE', labelEn: 'Share Type', labelGu: 'શેરનો પ્રકાર', columnType: 'TEXT_SHORT', sequence: 3 },
            { code: 'COL_SHARE_COUNT', labelEn: 'No. of Shares', labelGu: 'શેરની સંખ્યા', columnType: 'NUMBER', sequence: 4 },
            { code: 'COL_FACE_VALUE', labelEn: 'Face Value', labelGu: 'શેરની દાશંગિક કિંમત', columnType: 'CURRENCY', sequence: 5 },
            { code: 'COL_HELD_AMOUNT', labelEn: 'Total Held Amount', labelGu: 'ધારણ કરેલ શેરની કુલ રકમ', columnType: 'CURRENCY', sequence: 6 },
            { code: 'COL_LAST_DIV_YEAR', labelEn: 'Last Dividend Year', labelGu: 'છેલ્લુ ડિવિ. મેળવ્યુ તે વર્ષ', columnType: 'TEXT_SHORT', sequence: 7 },
            { code: 'COL_DIV_AMOUNT', labelEn: 'Dividend Amount (Rs.)', labelGu: 'ડિવિડન્ડની રકમ રૂ.', columnType: 'CURRENCY', sequence: 8 },
            { code: 'COL_DIV_REASON', labelEn: 'If declared but not received, reasons', labelGu: 'ડિવિ. બાહેર થયું હોય અને જો મેળવ્યુ ન હોય તો તેના કારણો જણાવો', columnType: 'TEXT_LONG', sequence: 9 },
          ],
        },
      ],
    },
    {
      code: 'SEC_MD_MANAGING_COMMITTEE',
      titleEn: 'Managing Committee Constitution & Bye-law Compliance',
      titleGu: 'મંડળીની સામાન્ય વ્ય. કમિટિની રચના અંગે પેટા નિયમ મુજબ અમલ',
      sequence: 7,
      fields: [
        { code: 'FLD_MD_AGM_HELD', labelEn: 'Last year AGM held? On time? If not, details & reasons', labelGu: 'છેલ્લા વર્ષની વાર્ષિક સાધારણ સભા મળીગઈ છે કે કેમ અને આવી સભા મુદતસર મળે છે કે કેમ? તે જણાવો, તેમજ મુદતસર ન મળી હોય તો તેની વિગત તથા કારણો જણાવો', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_MD_MEETING_PROCEEDINGS', labelEn: 'Proceedings of general & special meetings during inspection: any against bye-laws / bank conditions / agreement?', labelGu: 'તપાસણી સમય દરમ્યાન મળેલ સા. સભા તથા ખા. સા. સભાની કાર્યવાહી તપાસી કોઈ પેટા નિયમ વિરુદ્ધ કે બેન્કની શરતો કે કરાર વિરુદ્ધ જણાય તો તેની વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 2 },
        { code: 'FLD_MD_BYELAW_BREACH', labelEn: 'Bye-laws being violated / not implemented: number & details', labelGu: 'મંડળીના જે પેટા નિયમનો ભંગ થતો હોય તે અંગે તેમજ પેટાનિયમ ભંગિબનો અમલ થતો ન હોય તો તેના નંબર તથા વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 3 },
        { code: 'FLD_MD_MC_SIZE', labelEn: 'MC members required as per bye-laws vs actual', labelGu: 'પેટા નિયમ મુજબ : વ્ય. કમિટિમાં કેટલા સભ્યો હોવા જોઈએ અને કેટલા છે તે જણાવો', fieldType: 'TEXT_SHORT', sequence: 4 },
        { code: 'FLD_MD_MC_CONSTITUTION', labelEn: 'MC constitution date, AGM date, election rules, rotation vs whole committee, new members elected, any objectionable in proceedings', labelGu: 'મંડળીની વ્ય. કમિટિની રચના થઈ તે તા. સા. સભાની તારીખ જણાવો. ચૂંટણીના અલગ નિયમો છે ? વ્ય. કમિટિની રચના પેટા નિયમ મુજબ બરાબર થઈ છે ? ચૂંટણીની તકરારનો કોઈ મુદ્દો હોય તો વિગત જણાવો. રોટેશન મુજબ ચૂંટણી થઈ છે કે આખી કમિટિની ? કેટલા નવા સભ્યોની ચૂંટણી થઈ ? ચૂંટણી થતા વ્ય. કમિટિમાં કેટલા સભ્યો થયા ? સમગ્ર કાર્યવાહીમાં કાંઈ પાંધાજનક હોય તો વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 5 },
        { code: 'FLD_MD_MC_DISQUALIFIED', labelEn: 'Disqualified members continuing in MC: name-wise details, bye-law, reason; any against Section 32', labelGu: 'વ્ય. કમિટિમાં ગેરલાયકાત ધરાવતા કોઈ સભ્યો ચાલુ હોય તો તેની નામવાર વિગત જણાવો તથા ક્યા પેટા નિયમ મુજબ શું ગેર લાયકાત થયેલ છે અને તેને કમિટિમાં કેમ ચાલુ રાખ્યા છે તે જણાવો. કાનુન ૩૨ વિરુદ્ધના કોઈ સભ્ય વ્ય. કમિટિમાં ચાલુ હોય તો નામ સાથે વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 6 },
        { code: 'FLD_MD_MC_MEETINGS', labelEn: 'Dates of each MC meeting during inspection; regular as per bye-laws?', labelGu: 'તપાસણી દરમ્યાન વ્ય. કમિટિની પ્રત્યેક મિટીંગ કઈ કઈ તારીખે મળી તે જણાવો તેમજ આવી મિટીંગો પેટા નિયમ મુજબ નિયમિત ન મળતી હોય તો વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 7 },
        { code: 'FLD_MD_MINUTE_BOOK', labelEn: 'Minute book: objectionable resolution or against bank agreement/condition; verify sanctioned loan resolutions against minute book', labelGu: 'વ્ય. કમિટિની મીનીટબુક પાંચી કોઈ ઠરાવ પાંધાજનક હોય કે બેન્ક સાથેના કરાર કે શર્ત વિરુદ્ધ હોય તો જણાવો તથા બેન્કમાંથી મંજૂર કરાવેલ / ઉપાડેલ કર્જ તથા અન્ય કોઈ દસ્તાવેજો વિ. કરી આપેલ હોય તેની સાથે કરી આપેલ ઠરાવ કમિટિની મિનિટબુક સાથે તપાસી વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 8 },
        { code: 'FLD_MD_MC_NAMES_OUTSTANDING', labelEn: 'Submit MC names; any outstanding receivable from them? If so attach detail sheet (sample enclosed)', labelGu: 'વ્યવસ્થાપક કમિટિના નામ રજૂ કરો તેમની પાસે બાકી લેણું નીકળે છે ? હોય તો તે અંગેના વિતવાર પત્રક રજૂ કરો. (નમુનો સામેલ છે.)', fieldType: 'TEXT_LONG', sequence: 9 },
      ],
    },
    {
      code: 'SEC_MD_STAFF',
      titleEn: 'Society Staff / Secretary',
      titleGu: 'મંડળીના કર્મચારી અંગેની માહિતી',
      sequence: 8,
      fields: [
        { code: 'FLD_MD_SEC_OTHER_JOB', labelEn: 'Secretary works in other society / other job / business? Where & salary; salary as per Vaidhnath committee norms vs turnover & expenditure', labelGu: 'મંડળીના મંત્રી અન્ય મંડળીમાં મંત્રી તરીકે કે બીજો નોકરી કે બીજો ધંધો કરતા હોય તો ક્યાં ? અને ત્યાં મેળવતા પગારની વિગત જણાવો. તેમજ વૈધનાથન કમિટિની ભલામણો મુજબ મંડળીના કામકાજ તેમજ આપક સામે થયેલ ખર્ચની ટકાવારીના પ્રમાણમાં પગાર મેળવે છે કે કેમ ? તે જણાવો. મંડળીની આપક કરતા પગાર ખર્ચ અને અન્ય ખર્ચ વધુ જણાય તો અલગથી જણાવો', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_MD_SEC_FULLTIME', labelEn: 'Secretary full-time & independent? Bank approval letter no, date & validity', labelGu: 'મંત્રી કુલ ટાઈમ અને સ્વતંત્ર છે કે કેમ તે જણાવો તથા મંત્રી ભિમપુંક અંગેની બેન્કની માન્યતાની મંજૂરી પત્ર નંબર તારીખ તથા મુદત જણાવો', fieldType: 'TEXT_LONG', sequence: 2 },
      ],
    },
    {
      code: 'SEC_MD_RECORDS',
      titleEn: 'Society Records & Books',
      titleGu: 'મંડળીના રેકર્ડ અંગેની માહિતી',
      sequence: 9,
      fields: [
        { code: 'FLD_MD_BRANCHES_DAILY', labelEn: 'Separate branches? Daily books separate? Accounts as per CAS? Computerized daily book with paging, printout with round seal & officer sign/stamp filed?', labelGu: 'મંડળીની અલગ અલગ બ્રાન્ચો હોય તો કઈ કઈ અને તેના રોજમેળ અલગ અલગ રહે છે કે કેમ તે જણાવો. મંડળીમાં (CAS) કોમન એકાઉન્ટીંગ સીસ્ટમ મુજબ એકાઉન્ટ લખવામાં આવેલ છે. તે તપાસો. રોજમેળ કોમ્પ્યુટરરાઈઝ રાખવામાં આવેલ છે ? જો હા તો કોમ્પ્યુટરરાઈઝ રોજમેળને પેજિંગ નંબર આપીને તેની પ્રિન્ટઆઉટ કાઢી મંડળીના રાઉન્ડ સીલ સાથે મંડળીના જવાબદાર અધિકારીના સહી સિક્કા સાથે ફાઈલ રાખેલ છે. તે તપાસો અને પ્રિન્ટ આઉટ સહી સિક્કા સાથે ન હોય તો અલગ નોંધ લખો', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_MD_DAILY_UPTODATE', labelEn: 'Each daily book written up to last date? If pending, details & reasons', labelGu: 'દરેક રોજમેળ છેલ્લી તારીખ સુધીની લખેલ છે કે કેમ ? બાકી હોય તો તેની વિગત તથા કારણો જણાવો', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_MD_REGISTERS_UPTODATE', labelEn: 'Daily sale registers, stock registers & ledgers up to date? Stock register correctly written from daily book; state errors', labelGu: 'દૈનિક વેચાણ રજિસ્ટરો અને સ્ટોક રજિસ્ટરો તથા ખાતાવહીઓ છેલ્લી તારીખ સુધીની લખાયેલ છે કે કેમ ? અને બાકી હોય તો તેની વિગત જણાવો રોજમેળ પરથી સ્ટોક રજિસ્ટર બરાબર લખ્યાનું પણ તપાસી ત્રુટી હોય તો જણાવો', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_MD_RECORD_CUSTODY', labelEn: 'Records kept systematically in office? Responsibility fixed? If not, reasons; arrange & attach responsibility order copy', labelGu: 'મંડળીનું રેકર્ડ ઓફીસમાં વ્યવસ્થિત રખાય છે કે કેમ ? અને તે અંગેની જવાબદારી નક્કી થયેલ છે કે કેમ ? અને ન થયેલ હોય તો તેના કારણો જણાવો તેમજ તે અંગે ઘટતી વ્યવસ્થા કરાવીને જણાવો તેમજ જવાબદારીના હરાપની નકલ સામેલ કરો', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_MD_BOOKS_COMPLETE', labelEn: 'Member register, share ledger, loan ledger, general ledger, agreement register etc. written regularly & completely? Interest calculation correct in loan ledger? Attach department-wise summaries', labelGu: 'સભાસદ રજિસ્ટર, શેરખાતાવહી, કર્જ ખાતાવહી, સામાન્ય ખાતાવહી, એકરારનામા રજિસ્ટર વિ. ચોપડાઓ નિયમિત અને પૂર્ણ લખાયેલ છે કે કેમ ? અને ક્ષતિ હોય તો જણાવો વ્યક્તિગત કર્જ ખાતાવહીમાં વ્યાજની ગણત્રી બરાબર છે કે કેમ ? તે પણ તપાસો અને ત્રુટી હોય તો જણાવો તેમજ દરેક વિભાગના સરવૈયા તૈયાર કરાવી સામેલ રાખો', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_MD_DEADSTOCK', labelEn: 'Dead stock register maintained? Verify listed items & note', labelGu: 'ડેડસ્ટોક રજિસ્ટર રાખવામાં આવેલ છે કે કેમ તથા તેમાં જણાવેલ વસ્તુઓની ખરાઈ કરી તે અંગેની નોંધ કરો', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_MD_INDIVIDUAL_BALANCE', labelEn: 'Individual account balances tally with general ledger? If difference, details', labelGu: 'મંડળીના વ્યક્તિગત ખાતાઓના બેલેન્સ સામાન્ય ખાતાવહી સાથે મળે છે કે કેમ ? અને તફાવત હોય તો તેની વિગત જણાવો', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_MD_BANK_BALANCE', labelEn: 'Bank deposit & loan account balances in books tally with bank passbook? If difference, note', labelGu: 'મંડળીના ચોપડામાં બેન્ક સાથેના થાપણા અને ધિરાણ ખાતાઓના બેલેન્સ બેન્કની પાસબુક સાથે મળેલ છે કે કેમ ? અને તફાવત હોય તો નોંધ કરો', fieldType: 'RADIO_YN', sequence: 8 },
        { code: 'FLD_MD_OTHER_INDIVIDUAL', labelEn: 'Other individual accounts credit/debit outstanding tally with respective person/institution books? If difference, details', labelGu: 'અન્ય જે વ્યક્તિગત ખાતે જમા / ઉધાર બાકી હોય તે જે વ્યક્તિ / સંસ્થાના ચોપડા સાથે મેળવેલ છે કે કેમ ? અને તફાવત હોય તો તેની વિગત જણાવો', fieldType: 'RADIO_YN', sequence: 9 },
      ],
    },
    {
      code: 'SEC_MD_SHARES_DEPOSITS_INVEST',
      titleEn: 'Shares Returned, Deposits Accepted & Investments',
      titleGu: 'મંડળીએ સભ્યોને પરત કરેલ શેર, સ્વીકારેલ થાપણો અને જમીનગીરીમાં કરેલ રોકાણની માહિતી',
      sequence: 10,
      fields: [
        { code: 'FLD_MD_SHARE_INVEST_REG', labelEn: 'Register of shares & mortgage investment checked & correctly written?', labelGu: 'શેર અને જમીનગીરીમાં કરેલ રોકાણનું રજિસ્ટર તપાસો અને તે બરાબર લખાયેલ છે કે કેમ ? તે જણાવો', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_MD_SHARE_RETURN', labelEn: 'Shares returned during inspection within bye-law limit? Bank permission obtained? Returned share certificates cancelled & kept in society records?', labelGu: 'તપાસણી સમય દરમ્યાન મંડળી તરફથી પરત આપવામાં આવેલ શેરની રકમની વિગત તપાસો તે પેટા નિયમની મર્યાદામાં છે કે કેમ ? શેર પરત કરવા અંગે ની બેન્કની પરવાનગી મેળવેલ છે કે કેમ તેની નોંધ કરો તે અંગેના પરત મેળવેલ શેર સર્ટિ રદ કરી મંડળીના દફ્તરે રાખેલ છે કે કેમ ? તે જણાવો', fieldType: 'TEXT_LONG', sequence: 2 },
        { code: 'FLD_MD_DEPOSITS', labelEn: 'Deposits accepted consistent with bye-laws? Rules fixed? Obtain sheet of deposits accepted/returned during inspection & state details', labelGu: 'મંડળીએ સ્વીકારેલ થાપણો પેટા નિયમ સાથે સુસંગત છે કે કેમ ? તથા તે અંગેના કોઈ નિયમો નક્કી કરેલ છે કે કેમ તેની નોંધ કરો તથા મંડળીએ તપાસણી દરમ્યાન જે કોઈની થાપણો સ્વીકારી હોય અથવા પરત કરી હોય તેની વિગત સાથેનું પત્રક મેળવી તેની વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 3 },
        { code: 'FLD_MD_PROPERTY_INVEST', labelEn: 'Investment in movable/immovable property verified; mortgage/documents filed systematically? Any encumbrance? Necessary permission taken?', labelGu: 'મંડળીએ રચાવર જંગમ મિલકતમાં કરેલ રોકાણની વિગત તપાસો તથા તે અંગેની જમીનગીરી અગર દસ્તાવેજો મેળવી વ્યવસ્થિત ફાઈલે રાખેલ છે કે કેમ તેની નોંધ કરો. આવી મિલકત ઉપર કોઈ બોજો ઉત્પન કરેલ છે કે કેમ ? તેની ખરાઈ કરો તેમજ તે અંગે જરૂરી મંજૂરી લીધી છે કે કેમ ? તેની નોંધ કરો', fieldType: 'TEXT_LONG', sequence: 4 },
        { code: 'FLD_MD_OTHER_PROPERTY', labelEn: 'Other property: note & check its register', labelGu: 'અન્ય મિલકત હોય તો તેની નોંધ અને તેનું રજિસ્ટર તપાસો', fieldType: 'TEXT_LONG', sequence: 5 },
      ],
    },
    {
      code: 'SEC_MD_STOCK_SILAK_VERIFY',
      titleEn: 'Stock & Silak Verification Details',
      titleGu: 'સ્ટોક અને સિલક તપાસચા અંગેની માહિતી',
      sequence: 11,
      fields: [
        { code: 'FLD_MD_STOCK_VERIFY', labelEn: 'Stock register completed, stock verified on inspection date, signed & shared on page; stock correct? Excess/short details; attach category-wise stock sheet', labelGu: 'સ્ટોક રજિસ્ટર પૂર્ણ કરાવીને તપાસણીની તારીખનો સ્ટોક તપાસીને તે અંગે સ્ટોક રજિસ્ટરમાં જે તે પાને સહી અને શેરો કરો સ્ટોક બરોબર છે કે કેમ ? તે જણાવો અને જો વધ/ઘટ હોય તે વિગત જણાવો. અને સ્ટોક પત્રક સ્ટોક તપાસચાના શેરા સાથે સામેલ રાખો પ્રકારવાર રોકડ શાખ સામેનું સ્ટોક પત્રક અલગ અલગ નમુના પ્રમાણે મેળવવું', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_MD_STOCK_RESPONSIBILITY', labelEn: 'Goods stock responsibility fixed to specific persons? Regular verification by MC member / stock committee? Signed & shared in stock register?', labelGu: 'માલ સ્ટોકની જવાબદારી ચોક્કસ વ્યક્તિઓની નક્કી થયેલ છે કે કેમ તેમજ મંડળીના માલ સ્ટોકની વ્ય. કમિટિના સભ્ય અગર તે અંગે નિમાયેલ સ્ટોક કમિટિ તરફથી ચકાસણી નિયમિત થયેલ છે કે કેમ ? અને તે અંગે તેઓએ સ્ટોક રજિસ્ટરમાં શેરો કરી સહીઓ કરેલ છે કે કેમ તે જણાવો', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_MD_OBSOLETE_STOCK', labelEn: 'Old/obsolete stock: details & reasons', labelGu: 'જૂનો પડતર સ્ટોક હોય તો તે અંગેની વિગત અને આ સ્ટોક ક્યા કારણોસર પડતર છે તે જણાવો', fieldType: 'TEXT_LONG', sequence: 3 },
        { code: 'FLD_MD_SILAK_VERIFY', labelEn: 'Each department daily book completed & silak verified with sign & share; silak correct? If not presented / presented late, details; attach responsible person statement', labelGu: 'દરેક વિભાગના રોજમેળ પૂર્ણ કરાવીને તે તારીખની સિલક તપાસી તે અંગે રોજમેળમાં જે તે પાને સહી અને શેરો સિલક બરાબર છે કે કેમ ? અને જો સિલક રજુ થયેલ ન હોય કે પછી રજુ થયેલ કે પાછળથી રજુ થયેલ હોય તો તે વિગત જણાવો તથા તે અંગે જવાબદારનું નિવેદન મેળવી સામેલ રાખો', fieldType: 'TEXT_LONG', sequence: 4 },
        { code: 'FLD_MD_COMPUTER_PRINT_SIGN', labelEn: 'If computerized daily book, daily printout copies carry round seal with secretary/president sign & stamp?', labelGu: 'જો કોમ્પ્યુટરરાઈઝ રોજમેળ રાખેલ હોય તો તેની દરરોજ પ્રિન્ટ આઉટ કાઢેલ નકલમાં મંડળીના રાઉન્ડ સીલ સાથે મંત્રી/પ્રમુખના સહી સિક્કા કરેલ છે કે કેમ ?', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_MD_SILAK_DETAIL', labelEn: 'Silak presented: amount, date, presenter name, within limit? If excess silak kept, details', labelGu: 'વિગતવાર રજુ થયેલ સિલકની રકમ, તારીખ અને રજુ કરનારનું નામ તથા મર્યાદામાં છે કે કેમ તેની વિગત જણાવો સિલક વધારે રાખવામાં આવતી હોય તો તે અંગેની વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 6 },
        { code: 'FLD_MD_CLOSING_SILAK_DATE', labelEn: 'Closing silak date', labelGu: 'તા. ની બંધ સિલક', fieldType: 'DATE', sequence: 7 },
        { code: 'FLD_MD_CLOSING_SILAK_AMT', labelEn: 'Closing silak amount (Rs.)', labelGu: 'બંધ સિલક રૂ.', fieldType: 'CURRENCY', sequence: 8 },
        { code: 'FLD_MD_SILAK_PRESENTED_BY', labelEn: 'Presented by (name & designation)', labelGu: 'રજુ કરનાર શ્રી / હોદ્દો', fieldType: 'TEXT_SHORT', sequence: 9 },
        { code: 'FLD_MD_DAILYBOOK_PAGE', labelEn: 'Daily book page number', labelGu: 'રોજમેળ પાના નંબર', fieldType: 'TEXT_SHORT', sequence: 10 },
        { code: 'FLD_MD_STOCK_ORDER', labelEn: 'Goods stock responsibility fixed jointly on store keeper & secretary by proper order; give order no, date, name', labelGu: 'માલ સ્ટોક અંગેની જવાબદારી સ્ટોર્સ સંભાળનાર તથા મંડળીના મંત્રીની સંયુક્ત રીતે નક્કી થયેલ હોવી જોઈએ તેમજ યોગ્ય હરાપથી નક્કી થયેલ છે કે કેમ ? તેના હરાપ નંબર તારીખ અને નામ જણાવો', fieldType: 'TEXT_LONG', sequence: 11 },
        { code: 'FLD_MD_STOCK_BUILDING_INSURANCE', labelEn: 'Goods stock kept in rented or owned building (how much each)? Full value insurance taken? Verify & state', labelGu: 'માલ સ્ટોક ભાડાના કે માલીકીના મકાનમાં રાખવામાં આવેલ છે અને તે પૈકીના કેટલા ભાડાના અને માલીકીના તે જણાવો તેમજ માલ સ્ટોકનો પુરી રકમનો વીમો ઉતરાવેલ છે કે કેમ ? તે ચકાસીને જણાવો', fieldType: 'TEXT_LONG', sequence: 12 },
      ],
    },
    {
      code: 'SEC_MD_INSURANCE',
      titleEn: 'Silak & Goods Insurance',
      titleGu: 'સિલક અને માલના વિમા અંગેની માહિતી',
      sequence: 12,
      fields: [
        { code: 'FLD_MD_PACKAGE_POLICY', labelEn: 'Package policy amount & maturity date', labelGu: 'પેકેજ પોલીસીની રકમ અને તેની પાકતી તારીખ જણાવો', fieldType: 'TEXT_SHORT', sequence: 1 },
        { code: 'FLD_MD_FULL_INSURANCE', labelEn: 'Full-value insurance taken for cash in hand, silak transit, goods stock fire & riot? State amount & maturity; policy deposited with bank?', labelGu: 'મંડળીએ હાથ પરની સિલક, સિલકની હેર ફેર માટેનો તથા માલ સ્ટોકનો આગ તેમજ હુલ્લડનો વિમો પૂરી રકમનો લીધેલ છે કે કેમ ? તે અંગે વિમાની રકમ તથા પાકની મુદત જણાવો તથા પોલીસી બેન્કમાં સોંપેલ છે કે કેમ ? તે જણાવો', fieldType: 'RADIO_YN', sequence: 2 },
      ],
    },
    {
      code: 'SEC_MD_BANK_LOAN_RULES',
      titleEn: 'Bank Loan & Member Credit Rule Compliance',
      titleGu: 'બેન્ક માંથી મેળવેલ કર્જ તથા સભ્યોને કરેલ ધિરાણ અંગેના નિયમોનું પાલન',
      sequence: 13,
      fields: [
        { code: 'FLD_MD_LOAN_DOCS', labelEn: 'Loan documents (karjakhat), promise notes & other docs complete & correct; shares taken proportionate to credit? State errors', labelGu: 'તપાસણીના સમય દરમ્યાન મંડળીએ કરેલ ધિરાણના કર્જખત વિ. બરાબર છે કે કેમ ? તેમજ ધિરાણના કર્જખત વચન ચીઠ્ઠી, અન્ય દસ્તાવેજોમાં સંપૂર્ણ વિગત ભરેલ છે અને ધિરાણના પ્રમાણમાં સભાસદ પાસેથી શેર વિ. બરાબર લીધેલ છે કે કેમ તે તપાસો અને ત્રુટી હોય તો વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_MD_PROPERTY_CARDS', labelEn: 'How many members property cards made? Verified after making with share; give new account holder details', labelGu: 'મિલકત પત્રક કેટલા સભ્યોનું બનાવેલ છે તે જણાવો અને મિલકત પત્રક બન્યા પછી મિલકત પત્રકની ખરાઈ કરેલ છે તેના શેરા સાથે મિલકત પત્રકની ચકાસણી કરી નવા દાખલ થયેલ ખાતેદારની વિગત જણાવો', fieldType: 'TEXT_LONG', sequence: 2 },
        {
          code: 'FLD_MD_AGREEMENT_GRID', labelEn: 'Agreements under Sec 49 & 7/12 encumbrance certified xerox', labelGu: 'એકરારનામા કલમ ૪૯ તથા ૭/૧૨ બોજાનોંધ પ્રમાણીત ઝેરોક્ષ નકલ', fieldType: 'GRID', sequence: 3,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'અ.નં.', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_DETAIL', labelEn: 'Detail', labelGu: 'વિગત', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_SMALL', labelEn: 'Small Farmers', labelGu: 'નાના ખેડૂત', columnType: 'NUMBER', sequence: 3 },
            { code: 'COL_OTHER', labelEn: 'Other Farmers', labelGu: 'અન્ય ખેડૂત', columnType: 'NUMBER', sequence: 4 },
          ],
          seedRows: [
            { sr: 1, detail: 'ખેડૂત સભાસદોની સંખ્યા', small: '', other: '' },
            { sr: 2, detail: 'તે પૈકી કર્જ લેતા સભ્યો', small: '', other: '' },
            { sr: 3, detail: 'મેળવેલ એકરારનામા તથા ૭/૧૨ માં બોજાનોંધની પ્રમાણીત ઝેરોક્ષ નકલ', small: '', other: '' },
            { sr: 4, detail: 'તે પૈકી કર્જ લેતા સભ્યોના એકરારનામા તથા ૭/૧૨ માં બોજાનોંધની પ્રમાણીત ઝેરોક્ષ નકલ', small: '', other: '' },
            { sr: 5, detail: 'કર્જ લેતા સભ્યોના એકરાર નામામાં મેળવવા બાકી તથા ૭/૧૨ માં બોજાનોંધની પ્રમાણીત ઝેરોક્ષ નકલ', small: '', other: '' },
            { sr: 6, detail: 'મેળવેલ એકરાર નામા પૈકી તલાટી દફ્તરે નોંધ થવા કેટલા બાકી ?', small: '', other: '' },
          ],
        },
        { code: 'FLD_MD_MEDIUM_TERM_MORTGAGE', labelEn: 'Medium-term credit members mortgage (girokhat) taken? If pending how many, note', labelGu: 'મધ્યમુદત ધિરાણ અંગેના સભ્યોના ગીરોખત કરાવી લેવામાં આવેલ છે કે કેમ ? અગર કેટલા બાકી તેની નોંધ કરો', fieldType: 'TEXT_LONG', sequence: 4 },
        { code: 'FLD_MD_SANCTION_CONDITIONS', labelEn: 'If loan withdrawn from bank, sanction letter conditions complied? Note & state errors', labelGu: 'બેન્ક માંથી કર્જ ઉપાડેલ હોય તો તેના મંજૂરી પત્રની શરતોનું પાલન થયેલ છે કે કેમ તે અંગેની નોંધ કરો અને ત્રુટી હોય તો જણાવો', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_MD_DISBURSEMENT_SLIPS', labelEn: 'Each disbursement slip of credit withdrawn from bank obtained? Note & state errors', labelGu: 'બેન્કમાંથી ઉપાડેલ ધિરાણના પ્રત્યેક ચુકાદા પત્રકો મેળવી લેવામાં આવેલ છે કે કેમ તેની નોંધ કરો અને ત્રુટી હોય તો જણાવો', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_MD_BORROWER_VERIFICATION', labelEn: 'Borrowers called & credit verified; account statement given; arrange 100% defaulter verification; objectionable statements obtained & sent; society instructed', labelGu: 'કર્જદારોને બોલાવી બની શકે તેટલાની ધિરાણ અંગેની ખરાઈ કરી તેના ખા.પા. જણાવો અને વર્ષ દરમ્યાન ૧૦% બાકીદારોની ખરાઈ થાય તે પ્રમાણેની તજવીજ કરવી ખરાઈની રજુઆત દરમ્યાન જે કાંઈ પાંધાજનક જણાય તેનું નિવેદન મેળવીને મોકલી આપો અને મંડળીને ઘટતી સુચના આપો', fieldType: 'TEXT_LONG', sequence: 7 },
        { code: 'FLD_MD_TOTAL_MEMBERS', labelEn: 'Total members of society', labelGu: 'મંડળીની કુલ સભ્યોની સંખ્યા', fieldType: 'NUMBER', sequence: 8 },
        { code: 'FLD_MD_SHADOW_ACCOUNTS', labelEn: 'Number of shadow accounts of members (credit from society, opened in bank)', labelGu: 'મંડળીમાંથી ધિરાણ મેળવતા અને બેન્કમાં ખોલવામાં આવેલ મંડળીના સભ્યોના શેડો એકાઉન્ટ ખાતાઓની સંખ્યા', fieldType: 'NUMBER', sequence: 9 },
        { code: 'FLD_MD_DECEASED_MEMBERS', labelEn: 'Deceased members dues recovered or heirs admitted? Other land of member taken in place? Verify & note', labelGu: 'મંડળીએ ગુજરીગયેલ સભાસદોને કમી કરી તેનું લેણું વસુલ કર્યુ છે અથવા તેમના વારસદારોને સભાસદ તરીકે દાખલ કરેલ છે ? અને ગુજરી ગયેલાને બદલે જે તે સભ્યના બીજ જમીન લેવાયેલ છે કે કેમ ? તે તપાસી તેની નોંધ કરો', fieldType: 'TEXT_LONG', sequence: 10 },
        { code: 'FLD_MD_INTEREST_RECOVERY', labelEn: 'Interest recovered from debtors correctly as per rules (10% verified)? Interest suspension details checked; note errors', labelGu: 'મંડળીએ કર્જદારોનું વ્યાજ નિયમ મુજબ બરોબર વસુલ લીધેલ છે કે કેમ તેને ૧૦% ખરાઈ કરી તફાવત હોય તો મંડળીને ઘટતી સુચના આપો મંડળીના ધિરાણ લેતા સભ્યોના ઇન્ટરેસ્ટ સસ્પેન્શનની વિગત તપાસો અને કોઈ ત્રુટી હોય તો તેની નોંધ કરી જણાવો', fieldType: 'TEXT_LONG', sequence: 11 },
      ],
    },
    {
      code: 'SEC_MD_KCC_CONDITIONS',
      titleEn: 'KCC / Short-term Credit Sanction Conditions & Margin',
      titleGu: 'બેન્કમાંથી મેળવેલ ટૂંકી મુદત KCC અને અન્ય ધિરાણની શરતો તથા માર્જીન',
      sequence: 14,
      fields: [
        { code: 'FLD_MD_KCC_CONDITIONS', labelEn: 'All conditions of KCC / short-term & other credit sanction letters complied? Verify & state errors', labelGu: 'બેન્કમાંથી મેળવેલ ટૂંકી મુદત KCC અને અન્ય પ્રકારના તમામ ધિરાણના મંજૂરી પત્રની/વિવિધ પ્રકારની રોકડ શાખ અંગેની મંજૂરી પત્રની તમામ શરતોનું પાલન થયુ છે કે કેમ ? તે તપાસો અને કોઈપણ પ્રકારની ત્રુટી હોય તો જણાવો', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_MD_MARGIN', labelEn: 'Irregular accounts without margin: details & remarks; obtain category-wise stock sheets & calculate margin; is margin visible? Share', labelGu: 'આ અંગે કોઈ ખાતા અવ્યવસ્થિત બનેલ હોય અને માર્જીન જણવાતુ ન હોય તો તેની વિગત જણાવો અને નિવારવા અંગેના તમારા રિમાર્કસ આપો, રોકડ શાખ વગર અલગ અલગ નિયત નમુનાના સ્ટોક પત્રકો મેળવી માર્જીનની ગણત્રી કરો માર્જીન જણવાય છે કે કેમ ? તે અંગે શેરો કરો', fieldType: 'TEXT_LONG', sequence: 2 },
        {
          code: 'FLD_MD_OVERDUE_RECOVERY_GRID', labelEn: 'Action to recover overdue receivables from members', labelGu: 'સભાસદો પાસેનું મંડળીનું મુદત વીતેલ લેણું વસુલ કરવા થયેલ કાર્યવાહી', fieldType: 'GRID', sequence: 3,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'અ.નં.', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_RECV_TYPE', labelEn: 'Receivable Type', labelGu: 'લેણાનો પ્રકાર', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_OD_COUNT', labelEn: 'Overdue Count', labelGu: 'મુદત વિતેલ બાકી સંખ્યા', columnType: 'NUMBER', sequence: 3 },
            { code: 'COL_OD_AMOUNT', labelEn: 'Overdue Amount', labelGu: 'મુદત વિતેલ બાકી રકમ', columnType: 'CURRENCY', sequence: 4 },
            { code: 'COL_106_COUNT', labelEn: 'Papers u/s 106 Count', labelGu: 'કલમ ૧૦૬ હેઠળ કરેલ કાગળો સંખ્યા', columnType: 'NUMBER', sequence: 5 },
            { code: 'COL_106_AMOUNT', labelEn: 'Papers u/s 106 Amount', labelGu: 'કલમ ૧૦૬ હેઠળ કરેલ કાગળો રકમ', columnType: 'CURRENCY', sequence: 6 },
            { code: 'COL_ARB_COUNT', labelEn: 'Arbitration Steps Count', labelGu: 'લવાદી રાહે લીધેલ પગલા સંખ્યા', columnType: 'NUMBER', sequence: 7 },
            { code: 'COL_ARB_AMOUNT', labelEn: 'Arbitration Steps Amount', labelGu: 'લવાદી રાહે લીધેલ પગલા રકમ', columnType: 'CURRENCY', sequence: 8 },
            { code: 'COL_REC_106_COUNT', labelEn: 'Recovered u/s 106 Count', labelGu: 'તે સામે મેળવેલ ૧૦૬ હેઠળ સંખ્યા', columnType: 'NUMBER', sequence: 9 },
            { code: 'COL_REC_106_AMOUNT', labelEn: 'Recovered u/s 106 Amount', labelGu: 'તે સામે મેળવેલ ૧૦૬ હેઠળ રકમ', columnType: 'CURRENCY', sequence: 10 },
            { code: 'COL_REC2_COUNT', labelEn: 'Recovered Count (2)', labelGu: 'તે સામે મેળવેલ સંખ્યા', columnType: 'NUMBER', sequence: 11 },
            { code: 'COL_REC2_AMOUNT', labelEn: 'Recovered Amount (2)', labelGu: 'તે સામે મેળવેલ રકમ', columnType: 'CURRENCY', sequence: 12 },
          ],
        },
        { code: 'FLD_MD_PROCLAMATION_PENDING', labelEn: 'Recovery not made after proclamation: case details with name & outstanding amount', labelGu: 'જાહેરનામા નીકળ્યા પછી પણ વસુલાત ન થઈ હોય તો તે કેઈસની વિગત નામ અને બાકી રકમ સાથે જણાવો', fieldType: 'TEXT_LONG', sequence: 4 },
        { code: 'FLD_MD_ARBITRATION_CASES', labelEn: 'Arbitration cases filed against principal defaulters & pending? Current status', labelGu: 'મંડળીએ મુ. વિ. બાકીદારો સામે લવાદ કેસ કરેલ છે અને મંડળીમાં લવાદ કેસો ચાલે છે ? ચાલતા હોય તો તે અંગેની ચાલુ પરિસ્થિતી જણાવો', fieldType: 'TEXT_LONG', sequence: 5 },
        { code: 'FLD_MD_NPA_PROVISION', labelEn: 'Doubtful/bad debt details; provision for principal o/s / NPA & overdue interest correct? Obtain NPA sheet, check as per govt circular; inform society in writing if error', labelGu: 'મંડળીનું કોઈ શકમંદ અને ખરાબ લેણું હોય તો તે તપાસીને વિગત જણાવો તથા આ અંગે મંડળીને ઘટતી સુચના આપો અને મંડળીના મુ. વિ. લેણા / NPA લેણા તથા મુદત વિતેલ વ્યાજ અનામતની કરેલ જોગવાઈ બરાબર કરેલ છે ? તે તપાસો અને મંડળી પાસેથી NPA નું પત્રક મેળવી સરકારશ્રીના પરિપત્ર મુજબ જોગવાઈ બરાબર છે કે કેમ ? અને જો કોઈપણ પ્રકારની ત્રુટી હોય તો મંડળીને લેખીત પત્રથી જાણ કરો', fieldType: 'TEXT_LONG', sequence: 6 },
      ],
    },
    {
      code: 'SEC_MD_VIABILITY',
      titleEn: 'Financial Viability & Irregularities',
      titleGu: 'મંડળીની અર્થ ક્ષમતા અંગે તેમજ ગેરરીતીઓ',
      sequence: 15,
      fields: [
        { code: 'FLD_MD_VIABLE', labelEn: 'Society viable? Negligence? If not viable, by when viable & negligence removed; efforts & progress; suggestions; last year cash branch sheet sanctioned & max short-term withdrawal', labelGu: 'મંડળી અર્થક્ષમ છે ? મંડળીમાં ઇગ્નેલેન્સ છે ? અર્થક્ષમ થઈ ન હોય પણ અર્થક્ષમ થવાની શક્યતા હોય તો ક્યાં સુધીમાં અર્થક્ષમ થશે અને ઇગ્નેલેન્સ કેટલા સમયમાં દૂર થશે તે અંગે મંડળીએ હાથ ધરેલ પ્રયાસોની વિગત તથા શું પ્રગતિ કરેલ છે તે જણાવો તેમજ મંડળીને જરૂરી સુચનો કરો ટૂંકી મુદત ધિરાણનું છેલ્લુ ક્યા વર્ષનું શાખ પત્રક મંજૂર કરાવી બેન્ક માંથી ધિરાણ મેળવેલ છે અને તે વર્ષે વધુમાં વધુ ટૂંકી મુદતનો ઉપાડ કેટલો કરેલ હતો ?', fieldType: 'TEXT_LONG', sequence: 1 },
        { code: 'FLD_MD_NON_FUNCTIONAL', labelEn: 'If non-functional unit: action to wind up / remove from existence & what remains; detailed separate report if needed', labelGu: 'મંડળી બીનકાર્યક્ષમ એકમ હોય તો ફડચામાં લઈ જવામાં અસ્તિત્વમાંથી દૂર કરવાની શું કાર્યવાહી થઈ છે અને હવે શું કરવાનું રહે છે તે જણાવો. જરૂરી હોય તો સવિસ્તાર અલગ રીપોર્ટ કરો', fieldType: 'TEXT_LONG', sequence: 2 },
        { code: 'FLD_MD_BANK_ADMIN', labelEn: 'Due to mismanagement & MC inactivity, opinion to take society under bank administration? Separate detailed report if needed', labelGu: 'મંડળીમાં ગરવહિવટ અને વ્ય. કમિટિની નિષ્ક્રિયતાને કારણે મંડળી બેન્કના વહિવટ હેઠળ લેવાનો અભિપ્રાય હોય તો જણાવો અને જરૂરી હોય તો અલગ અને વિગતવાર રોપોર્ટ કરો', fieldType: 'TEXT_LONG', sequence: 3 },
        { code: 'FLD_MD_IRREGULARITY', labelEn: 'Irregularity / malpractice noticed during inspection: details; separate report if needed', labelGu: 'મંડળીમાં ગેરરીતી કે ગોલમાલ તપાસણીના સમય દરમ્યાન જણાયેલ હોય તો તે અંગે વિગત આપો અને જરૂર હોય તો અલગ રીપોર્ટ કરો', fieldType: 'TEXT_LONG', sequence: 4 },
        { code: 'FLD_MD_PREV_IRREG_RECOVERY', labelEn: 'Previous irregularity/malpractice amount not recovered: responsible name, recoverable amount, details, action taken & pending', labelGu: 'આગલી ગેરરીતી અને ગોલમાલની રકમ વસુલ થઈ ન હોય તો જવાબદારનું નામ વસુલ કરવા પાત્ર રકમ અને વિગત તથા આ અંગે શું કાર્યવાહી થયેલ છે અને શું કરવાનું બાકી છે તે જણાવો', fieldType: 'TEXT_LONG', sequence: 5 },
      ],
    },
    {
      code: 'SEC_MD_CURRENT_RECOVERY',
      titleEn: 'Current Year Recoverables from Members',
      titleGu: 'મંડળીના સભ્ય પાસેનું ચાલુ વર્ષમાં વસુલાત પાત્ર લહેણાંની માહિતી',
      sequence: 16,
      fields: [
        {
          code: 'FLD_MD_CURRENT_RECOVERY_GRID', labelEn: 'Current year recoverable receivables', labelGu: 'ચાલુ વર્ષમાં વસુલાત પાત્ર લહેણાં', fieldType: 'GRID', sequence: 1,
          gridColumns: [
            { code: 'COL_SR', labelEn: 'Sr', labelGu: 'અ.નં.', columnType: 'NUMBER', sequence: 1 },
            { code: 'COL_RECV_TYPE', labelEn: 'Receivable Type', labelGu: 'લેણાનો પ્રકાર', columnType: 'TEXT_SHORT', sequence: 2 },
            { code: 'COL_DEMAND', labelEn: 'Recoverable Amount (Demand)', labelGu: 'વસુલાતપાત્ર રકમ (ડિમાન્ડ)', columnType: 'CURRENCY', sequence: 3 },
            { code: 'COL_RECOVERED', labelEn: 'Recovery up to date', labelGu: 'તે પૈકી તારીખ સુધીમાં થયેલ વસુલાત', columnType: 'CURRENCY', sequence: 4 },
            { code: 'COL_PCT', labelEn: 'Recovery %', labelGu: 'વસુલાતની ટકાવારી', columnType: 'PERCENTAGE', sequence: 5 },
            { code: 'COL_SHARE', labelEn: 'Share', labelGu: 'શેરો', columnType: 'TEXT_SHORT', sequence: 6 },
          ],
        },
      ],
    },
    {
      code: 'SEC_MD_ENCLOSURES',
      titleEn: 'Enclosures / Attachments',
      titleGu: 'સામેલ પત્રકો / બીડાણા',
      sequence: 17,
      fields: [
        { code: 'FLD_MD_ENC_1', labelEn: 'Daftar tapasani yadi sheets, stock sheet & summaries enclosed', labelGu: '(૧) દફ્તર તપાસણી યાદી સાથેના બીડાણાના પત્રકો તથા સ્ટોકપત્રક અને તારીજ - સરવૈયા સામેલ છે', fieldType: 'RADIO_YN', sequence: 1 },
        { code: 'FLD_MD_ENC_2', labelEn: 'Copy of letter to society re errors & suggestions enclosed', labelGu: '(૨) ક્ષતિઓ તથા સુચનો અંગે મંડળીને લખેલ પત્રની નકલ સામેલ છે', fieldType: 'RADIO_YN', sequence: 2 },
        { code: 'FLD_MD_ENC_3', labelEn: 'Outstanding receivables sheet enclosed', labelGu: '(૩) બાકીદારના લેણાની વિગતનું પત્રક સામેલ છે', fieldType: 'RADIO_YN', sequence: 3 },
        { code: 'FLD_MD_ENC_4', labelEn: 'Provision sheet for principal o/s / NPA enclosed', labelGu: '(૪) મંડળીએ મું વિ. / NPA લેણાની કરેલ જોગવાઈનું પત્રક', fieldType: 'RADIO_YN', sequence: 4 },
        { code: 'FLD_MD_ENC_5', labelEn: 'Stock sheet in prescribed cash-branch sample obtained & kept', labelGu: '(૫) રોકડ શાખાના પ્રકારપાઈઝ નિયત નમુનામાં સ્ટોકપત્રક મેળવી રાખેલ છે', fieldType: 'RADIO_YN', sequence: 5 },
        { code: 'FLD_MD_ENC_6', labelEn: 'Employees / managing committee list & receivables from them enclosed', labelGu: '(૬) મંડળીના કર્મચારીઓ / વ્યવસ્થાપક કમિટિનું લીસ્ટ તથા તેઓ પાસેના લેણાની માહિતી સામેલ છે', fieldType: 'RADIO_YN', sequence: 6 },
        { code: 'FLD_MD_ENC_7', labelEn: 'Sheet as per sample of point 4.2 prepared separately & enclosed', labelGu: '(૭) મુદા નં. ૪.૨ નમુના મુજબનું પત્રક અલગ બનાવી સામેલ રાખવું', fieldType: 'RADIO_YN', sequence: 7 },
        { code: 'FLD_MD_ENC_8', labelEn: 'True copies of necessary administration resolutions enclosed', labelGu: '(૮) મંડળીએ વહીવટ અંગેના કરેલ જરૂરી ઠરાવોની ખરી નકલો સામેલ છે', fieldType: 'RADIO_YN', sequence: 8 },
      ],
    },
    {
      code: 'SEC_MD_SIGNOFF',
      titleEn: 'Sign-off',
      titleGu: 'સહી',
      sequence: 18,
      fields: [
        { code: 'FLD_MD_PLACE', labelEn: 'Place', labelGu: 'મુકામ', fieldType: 'TEXT_SHORT', sequence: 1 },
        { code: 'FLD_MD_DATE', labelEn: 'Date', labelGu: 'તારીખ', fieldType: 'DATE', sequence: 2 },
        { code: 'FLD_MD_SIGN_NAME', labelEn: 'Name (Signature)', labelGu: 'નામ (સહી)', fieldType: 'TEXT_SHORT', sequence: 3 },
        { code: 'FLD_MD_SIGN_DESG', labelEn: 'Designation (Branch Manager / Branch In-charge)', labelGu: 'હોદ્દો : બ્રાન્ચ મેનેજર / શાખા ઈન્ચાર્જ', fieldType: 'TEXT_SHORT', sequence: 4 },
        { code: 'FLD_MD_AUDITOR_SIGNATURE', labelEn: 'Auditor Signature', labelGu: 'અધિકારીની સહી', fieldType: 'SIGNATURE', isMandatory: true, sequence: 5 },
      ],
    },
  ];

  template.sections = sections;
  await template.save();

  const AuditType = require('../models/AuditType');
  await AuditType.findByIdAndUpdate(auditType._id, { currentTemplateId: template._id });

  return template;
};
